// SPDX-License-Identifier: GPL-3.0-only
//
// Copyright (C) 2026 lurixo
//
// This program is free software: you can redistribute it and/or modify it under
// the terms of the GNU General Public License as published by the Free Software
// Foundation, version 3.
//
// This program is distributed in the hope that it will be useful, but WITHOUT ANY
// WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
// PARTICULAR PURPOSE. See the GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License along with
// this program. If not, see <https://www.gnu.org/licenses/>.

package com.aegis.ime.engine

internal object EmojiAssociations {

    class Row(val emoji: String, val names: String, val keys: String) {
        val keyList: List<String> get() = keys.split(' ')
        val primaryKey: String get() = keys.substringBefore(' ')
    }

    fun rows(): List<Row> =
        face() +
        hand() +
        flag() +
        animal() +
        plant() +
        food() +
        travel() +
        activity() +
        objects() +
        symbol()

    private fun face(): List<Row> = listOf(
        Row("😀", "咧嘴笑/嘿嘿", "liezuixiao heihei"),
        Row("😃", "哈哈/开心", "haha kaixin"),
        Row("😄", "大笑/哈哈/开怀大笑", "daxiao haha kaihuaidaxiao"),
        Row("😁", "呲牙/龇牙/露齿笑", "ciya ziya luchixiao"),
        Row("😆", "眯眼笑/哈哈大笑", "miyanxiao hahadaxiao"),
        Row("😅", "尬笑/流汗笑/苦笑", "gaxiao liuhanxiao kuxiao"),
        Row("😂", "笑哭/喜极而泣", "xiaoku xijierqi"),
        Row("🤣", "笑得打滚/笑翻/爆笑/笑死", "xiaodedagun xiaofan baoxiao xiaosi"),
        Row("🥲", "含泪微笑/苦中作乐", "hanleiweixiao kuzhongzuole"),
        Row("🥹", "强忍泪水/热泪盈眶", "qiangrenleishui releiyingkuang"),
        Row("☺️", "微笑/笑脸", "weixiao xiaolian"),
        Row("😊", "笑眯眯/害羞微笑", "xiaomimi haixiuweixiao"),
        Row("😇", "天使/光环天使", "tianshi guanghuantianshi"),
        Row("🙂", "微笑/呵呵/假笑", "weixiao hehe jiaxiao"),
        Row("🙃", "倒脸/翻转笑脸", "daolian fanzhuanxiaolian"),
        Row("😉", "眨眼/抛媚眼/使眼色", "zhayan paomeiyan shiyanse"),
        Row("😌", "欣慰/安心/舒心", "xinwei anxin shuxin"),
        Row("😍", "花痴/爱心眼", "huachi aixinyan"),
        Row("🥰", "幸福/被爱包围/满脸爱心", "xingfu beiaibaowei manlianaixin"),
        Row("😘", "飞吻/么么哒", "feiwen memeda"),
        Row("😗", "亲亲/嘟嘴", "qinqin duzui"),
        Row("😙", "眯眼亲亲/微笑亲吻", "miyanqinqin weixiaoqinwen"),
        Row("😚", "闭眼亲亲", "biyanqinqin"),
        Row("😋", "好吃/馋/美味", "haochi chan meiwei"),
        Row("😛", "吐舌/吐舌头", "tushe tushetou"),
        Row("😝", "眯眼吐舌/鬼脸", "miyantushe guilian"),
        Row("😜", "调皮/眨眼吐舌", "tiaopi zhayantushe"),
        Row("🤪", "搞怪/疯癫", "gaoguai fengdian"),
        Row("🤨", "挑眉/质疑/怀疑", "tiaomei zhiyi huaiyi"),
        Row("🧐", "单片眼镜/审视/观察", "danpianyanjing shenshi guancha"),
        Row("🤓", "书呆子/学霸", "shudaizi xueba"),
        Row("😎", "墨镜/得意/酷", "mojing deyi ku"),
        Row("🥸", "伪装/乔装", "weizhuang qiaozhuang"),
        Row("🤩", "星星眼/崇拜", "xingxingyan chongbai"),
        Row("🥳", "庆祝/派对", "qingzhu paidui"),
        Row("😏", "坏笑/斜眼笑/奸笑", "huaixiao xieyanxiao jianxiao"),
        Row("😒", "无语/不屑/不爽", "wuyu buxie bushuang"),
        Row("😞", "失望/沮丧", "shiwang jusang"),
        Row("😔", "低落/忧郁/难过", "diluo youyu nanguo"),
        Row("😟", "担心/担忧", "danxin danyou"),
        Row("😕", "困惑/疑惑", "kunhuo yihuo"),
        Row("🙁", "不开心/皱眉", "bukaixin zhoumei"),
        Row("☹️", "愁眉苦脸/皱眉脸", "choumeikulian zhoumeilian"),
        Row("😣", "纠结/忍耐", "jiujie rennai"),
        Row("😖", "苦恼/懊恼", "kunao aonao"),
        Row("😫", "累/疲惫/崩溃", "lei pibei bengkui"),
        Row("😩", "疲倦/哀嚎/无奈", "pijuan aihao wunai"),
        Row("🥺", "可怜/委屈巴巴/卑微", "kelian weiqubaba beiwei"),
        Row("😢", "哭/流泪/伤心", "ku liulei shangxin"),
        Row("😭", "大哭/嚎啕大哭/泪流满面", "daku haotaodaku leiliumanmian"),
        Row("😤", "哼/傲娇/不服气", "heng aojiao bufuqi"),
        Row("😠", "生气/发怒", "shengqi fanu"),
        Row("😡", "愤怒/气炸/暴怒", "fennu qizha baonu"),
        Row("🤬", "骂人/爆粗口", "maren baocukou"),
        Row("🤯", "脑袋爆炸/头炸了/炸裂", "naodaibaozha touzhale zhalie"),
        Row("😳", "脸红/害羞", "lianhong haixiu"),
        Row("🥵", "热死了/好热", "resile haore"),
        Row("🥶", "冻僵/冷死了/好冷", "dongjiang lengsile haoleng"),
        Row("😱", "尖叫/惊恐/吓死了", "jianjiao jingkong xiasile"),
        Row("😨", "害怕/恐惧", "haipa kongju"),
        Row("😰", "冷汗/焦虑", "lenghan jiaolv"),
        Row("😥", "失落/难过流汗", "shiluo nanguoliuhan"),
        Row("😓", "流汗/汗", "liuhan han"),
        Row("🤗", "抱抱/拥抱", "baobao yongbao"),
        Row("🤔", "思考/沉思/想想", "sikao chensi xiangxiang"),
        Row("🫣", "偷看/捂脸偷看", "toukan wuliantoukan"),
        Row("🤭", "捂嘴笑/偷笑", "wuzuixiao touxiao"),
        Row("🫢", "捂嘴惊讶", "wuzuijingya"),
        Row("🫡", "敬礼/收到", "jingli shoudao"),
        Row("🤫", "嘘/安静/保密", "xu anjing baomi"),
        Row("🫠", "融化/化了", "ronghua huale"),
        Row("🤥", "说谎/撒谎/匹诺曹", "shuohuang sahuang pinuocao"),
        Row("😶", "沉默/无话可说/没有嘴", "chenmo wuhuakeshuo meiyouzui"),
        Row("🫥", "隐身/透明人/消失", "yinshen toumingren xiaoshi"),
        Row("😐", "面无表情/冷漠", "mianwubiaoqing lengmo"),
        Row("🫤", "歪嘴/无可奈何", "waizui wukenaihe"),
        Row("😑", "面瘫/无表情", "miantan wubiaoqing"),
        Row("🫨", "摇晃/震动", "yaohuang zhendong"),
        Row("😬", "尴尬/龇牙咧嘴/咬牙", "ganga ziyaliezui yaoya"),
        Row("🙄", "翻白眼/白眼", "fanbaiyan baiyan"),
        Row("😯", "惊讶/哦", "jingya o"),
        Row("😦", "愕然/吃惊", "eran chijing"),
        Row("😧", "痛苦/惊愕", "tongku jinge"),
        Row("😮", "哇/张大嘴", "wa zhangdazui"),
        Row("😲", "震惊/目瞪口呆", "zhenjing mudengkoudai"),
        Row("🥱", "打哈欠/困/无聊", "dahaqian kun wuliao"),
        Row("😴", "睡觉/睡着/呼呼大睡", "shuijiao shuizhao huhudashui"),
        Row("🤤", "流口水/垂涎", "liukoushui chuixian"),
        Row("😪", "瞌睡/困了/打瞌睡", "keshui kunle dakeshui"),
        Row("😮‍💨", "叹气/松口气/呼气", "tanqi songkouqi huqi"),
        Row("😵", "晕/晕倒/昏倒", "yun yundao hundao"),
        Row("😵‍💫", "头晕眼花/蚊香眼/晕头转向", "touyunyanhua wenxiangyan yuntouzhuanxiang"),
        Row("🤐", "闭嘴/拉链嘴/封口", "bizui lalianzui fengkou"),
        Row("🥴", "醉了/迷糊/头晕", "zuile mihu touyun"),
        Row("🤢", "恶心/想吐", "exin xiangtu"),
        Row("🤮", "呕吐/吐了", "outu tule"),
        Row("🤧", "打喷嚏/阿嚏", "dapenti ati"),
        Row("😷", "口罩/戴口罩", "kouzhao daikouzhao"),
        Row("🤒", "发烧/生病/量体温", "fashao shengbing liangtiwen"),
        Row("🤕", "受伤/包扎/缠绷带", "shoushang baoza chanbengdai"),
        Row("🤑", "发财/见钱眼开/财迷", "facai jianqianyankai caimi"),
        Row("🤠", "牛仔/牛仔帽", "niuzai niuzaimao"),
        Row("😈", "小恶魔/恶魔", "xiaoemo emo"),
        Row("👿", "生气恶魔/愤怒恶魔", "shengqiemo fennuemo"),
        Row("👹", "恶鬼/红鬼/鬼怪", "egui honggui guiguai"),
        Row("👺", "天狗/长鼻子鬼", "tiangou changbizigui"),
        Row("🤡", "小丑", "xiaochou"),
        Row("💩", "便便/大便", "bianbian dabian"),
        Row("👻", "幽灵/鬼/鬼魂", "youling gui guihun"),
        Row("💀", "骷髅/骷髅头", "kulou kuloutou"),
        Row("☠️", "骷髅交叉骨/海盗标志/剧毒", "kuloujiaochagu haidaobiaozhi judu"),
        Row("👽", "外星人", "waixingren"),
        Row("👾", "小怪兽/外星怪物/像素怪", "xiaoguaishou waixingguaiwu xiangsuguai"),
        Row("🤖", "机器人", "jiqiren"),
        Row("🎃", "南瓜灯/万圣节南瓜", "nanguadeng wanshengjienangua"),
        Row("😺", "笑脸猫/开心猫", "xiaolianmao kaixinmao"),
        Row("😸", "眯眼笑猫/咧嘴笑猫", "miyanxiaomao liezuixiaomao"),
        Row("😹", "笑哭猫/猫笑哭", "xiaokumao maoxiaoku"),
        Row("😻", "爱心眼猫/花痴猫", "aixinyanmao huachimao"),
        Row("😼", "坏笑猫/得意猫", "huaixiaomao deyimao"),
        Row("😽", "亲亲猫", "qinqinmao"),
        Row("🙀", "惊恐猫/吓呆猫", "jingkongmao xiadaimao"),
        Row("😿", "哭泣猫/伤心猫", "kuqimao shangxinmao"),
        Row("😾", "生气猫/不爽猫", "shengqimao bushuangmao"),
    )

    private fun hand(): List<Row> = listOf(
        Row("👋", "挥手/再见/拜拜/打招呼", "huishou zaijian baibai dazhaohu"),
        Row("🤚", "手背/举手", "shoubei jushou"),
        Row("🖐️", "手掌/五指张开", "shouzhang wuzhizhangkai"),
        Row("✋", "举手/手掌/停止", "jushou shouzhang tingzhi"),
        Row("🖖", "瓦肯礼/瓦肯手势/星际迷航", "wakenli wakenshoushi xingjimihang"),
        Row("🫱", "右手/向右伸手", "youshou xiangyoushenshou"),
        Row("🫲", "左手/向左伸手", "zuoshou xiangzuoshenshou"),
        Row("🫳", "掌心向下/手掌朝下", "zhangxinxiangxia shouzhangchaoxia"),
        Row("🫴", "掌心向上/手掌朝上", "zhangxinxiangshang shouzhangchaoshang"),
        Row("🫷", "向左推/左手击掌", "xiangzuotui zuoshoujizhang"),
        Row("🫸", "向右推/右手击掌", "xiangyoutui youshoujizhang"),
        Row("👌", "好的/没问题/欧克", "haode meiwenti ouke"),
        Row("🤌", "捏手指/意大利手势", "nieshouzhi yidalishoushi"),
        Row("🤏", "一点点/捏合/少许/拿捏", "yidiandian niehe shaoxu nanie"),
        Row("✌️", "耶/剪刀手/胜利/比耶", "ye jiandaoshou shengli biye"),
        Row("🤞", "交叉手指/祈求好运/好运", "jiaochashouzhi qiqiuhaoyun haoyun"),
        Row("🫰", "比心/手指爱心", "bixin shouzhiaixin"),
        Row("🤟", "爱你手势/我爱你", "ainishoushi woaini"),
        Row("🤘", "摇滚/摇滚手势", "yaogun yaogunshoushi"),
        Row("🤙", "打电话手势/六六六", "dadianhuashoushi liuliuliu"),
        Row("👈", "向左/左边", "xiangzuo zuobian"),
        Row("👉", "向右/右边", "xiangyou youbian"),
        Row("👆", "向上/上面", "xiangshang shangmian"),
        Row("🖕", "中指/竖中指/鄙视", "zhongzhi shuzhongzhi bishi"),
        Row("👇", "向下/下面", "xiangxia xiamian"),
        Row("☝️", "食指/向上指/第一", "shizhi xiangshangzhi diyi"),
        Row("👍", "点赞/赞/大拇指/厉害", "dianzan zan damuzhi lihai"),
        Row("👎", "踩/弱/差评", "cai ruo chaping"),
        Row("✊", "拳头/加油/握拳", "quantou jiayou woquan"),
        Row("👊", "出拳/碰拳/拳头", "chuquan pengquan quantou"),
        Row("🤛", "左拳/碰拳", "zuoquan pengquan"),
        Row("🤜", "右拳/碰拳", "youquan pengquan"),
        Row("👏", "鼓掌/拍手/掌声", "guzhang paishou zhangsheng"),
        Row("🙌", "举双手/欢呼/万岁", "jushuangshou huanhu wansui"),
        Row("🫶", "比心/双手比心/爱心手势", "bixin shuangshoubixin aixinshoushi"),
        Row("👐", "张开双手/拥抱", "zhangkaishuangshou yongbao"),
        Row("🤲", "双手捧/捧", "shuangshoupeng peng"),
        Row("🤝", "握手/合作/成交", "woshou hezuo chengjiao"),
        Row("🙏", "祈祷/拜托/感谢/合十", "qidao baituo ganxie heshi"),
        Row("✍️", "写字/写作/记笔记", "xiezi xiezuo jibiji"),
        Row("💅", "美甲/指甲油/涂指甲", "meijia zhijiayou tuzhijia"),
        Row("🤳", "自拍", "zipai"),
        Row("💪", "肌肉/加油/强壮", "jirou jiayou qiangzhuang"),
        Row("🦾", "机械臂/机械手臂", "jixiebi jixieshoubi"),
        Row("🦿", "机械腿/假肢", "jixietui jiazhi"),
        Row("🦵", "腿/大腿", "tui datui"),
        Row("🦶", "脚/足", "jiao zu"),
        Row("👂", "耳朵", "erduo"),
        Row("🦻", "助听器/戴助听器", "zhutingqi daizhutingqi"),
        Row("👃", "鼻子", "bizi"),
        Row("🧠", "大脑/脑子", "danao naozi"),
        Row("🫀", "心脏", "xinzang"),
        Row("🫁", "肺/肺部", "fei feibu"),
        Row("🦷", "牙齿/牙", "yachi ya"),
        Row("🦴", "骨头/骨骼", "gutou guge"),
        Row("👀", "眼睛/围观/看", "yanjing weiguan kan"),
        Row("👁️", "一只眼睛/单眼/眼睛", "yizhiyanjing danyan yanjing"),
        Row("👅", "舌头", "shetou"),
        Row("👄", "嘴巴/嘴唇/红唇", "zuiba zuichun hongchun"),
        Row("🫦", "咬嘴唇/咬唇", "yaozuichun yaochun"),
        Row("👶", "婴儿/宝宝/小宝宝", "yinger baobao xiaobaobao"),
        Row("🧒", "儿童/小孩/孩子", "ertong xiaohai haizi"),
        Row("👦", "男孩/小男孩", "nanhai xiaonanhai"),
        Row("👧", "女孩/小女孩", "nvhai xiaonvhai"),
        Row("🧑", "人/成年人", "ren chengnianren"),
        Row("👨", "男人/男士", "nanren nanshi"),
        Row("👩", "女人/女士", "nvren nvshi"),
        Row("🧓", "老人/老年人", "laoren laonianren"),
        Row("👴", "爷爷/老爷爷/老头", "yeye laoyeye laotou"),
        Row("👵", "奶奶/老奶奶/老太太", "nainai laonainai laotaitai"),
        Row("🙍", "皱眉/不高兴", "zhoumei bugaoxing"),
        Row("🙎", "撅嘴/生气", "juezui shengqi"),
        Row("🙅", "不行/拒绝/不要", "buxing jujue buyao"),
        Row("🙆", "可以/没问题", "keyi meiwenti"),
        Row("💁", "傲娇/前台", "aojiao qiantai"),
        Row("🙋", "举手/举手发言", "jushou jushoufayan"),
        Row("🧏", "聋人/听障人士", "longren tingzhangrenshi"),
        Row("🙇", "鞠躬/道歉/磕头", "jugong daoqian ketou"),
        Row("🤦", "捂脸/扶额/无语", "wulian fue wuyu"),
        Row("🤷", "摊手/耸肩/无奈", "tanshou songjian wunai"),
        Row("👮", "警察/警官", "jingcha jingguan"),
        Row("🕵️", "侦探/特工/间谍", "zhentan tegong jiandie"),
        Row("💂", "卫兵/皇家卫兵", "weibing huangjiaweibing"),
        Row("🥷", "忍者", "renzhe"),
        Row("👷", "工人/建筑工人", "gongren jianzhugongren"),
        Row("🫅", "君主/国王", "junzhu guowang"),
        Row("🤴", "王子/太子", "wangzi taizi"),
        Row("👸", "公主/女王", "gongzhu nvwang"),
        Row("👳", "缠头巾/头巾", "chantoujin toujin"),
        Row("👲", "瓜皮帽", "guapimao"),
        Row("🧕", "穆斯林妇女/头巾", "musilinfunv toujin"),
        Row("🤵", "新郎/西装/礼服", "xinlang xizhuang lifu"),
        Row("👰", "新娘/婚纱/头纱", "xinniang hunsha tousha"),
        Row("🤰", "孕妇/怀孕", "yunfu huaiyun"),
        Row("🫃", "怀孕男人/吃撑", "huaiyunnanren chicheng"),
        Row("🫄", "怀孕/大肚子", "huaiyun daduzi"),
        Row("👼", "小天使/天使", "xiaotianshi tianshi"),
        Row("🎅", "圣诞老人/圣诞节", "shengdanlaoren shengdanjie"),
        Row("🤶", "圣诞奶奶/圣诞老奶奶", "shengdannainai shengdanlaonainai"),
        Row("🦸", "超级英雄/超人/英雄", "chaojiyingxiong chaoren yingxiong"),
        Row("🦹", "反派/超级反派/坏人", "fanpai chaojifanpai huairen"),
        Row("🧙", "魔法师/巫师/法师", "mofashi wushi fashi"),
        Row("🧚", "仙女/小仙女/精灵", "xiannv xiaoxiannv jingling"),
        Row("🧛", "吸血鬼", "xixuegui"),
        Row("🧜", "美人鱼/人鱼", "meirenyu renyu"),
        Row("🧝", "精灵/小精灵", "jingling xiaojingling"),
        Row("🧞", "灯神/神灯精灵", "dengshen shendengjingling"),
        Row("🧟", "僵尸/丧尸", "jiangshi sangshi"),
        Row("💆", "按摩/头部按摩", "anmo toubuanmo"),
        Row("💇", "理发/剪头发/剪发", "lifa jiantoufa jianfa"),
        Row("🚶", "走路/散步/步行", "zoulu sanbu buxing"),
        Row("🧍", "站立/站着", "zhanli zhanzhe"),
        Row("🧎", "下跪/跪/跪下", "xiagui gui guixia"),
        Row("🏃", "跑步/奔跑/快跑", "paobu benpao kuaipao"),
        Row("💃", "跳舞/热舞/舞蹈", "tiaowu rewu wudao"),
        Row("🕺", "蹦迪/尬舞/跳舞", "bengdi gawu tiaowu"),
        Row("👯", "兔女郎/双人舞", "tunvlang shuangrenwu"),
        Row("🧖", "桑拿/蒸桑拿/汗蒸", "sangna zhengsangna hanzheng"),
        Row("🧗", "攀岩/攀爬/爬山", "panyan panpa pashan"),
        Row("👬", "好兄弟/基友/男男牵手", "haoxiongdi jiyou nannanqianshou"),
        Row("👭", "闺蜜/好姐妹/女女牵手", "guimi haojiemei nvnvqianshou"),
        Row("👫", "情侣/牵手/约会", "qinglv qianshou yuehui"),
    )

    private fun flag(): List<Row> = listOf(
        Row("🏁", "格子旗/赛车旗/终点旗", "geziqi saicheqi zhongdianqi"),
        Row("🚩", "红旗/小红旗/旗子", "hongqi xiaohongqi qizi"),
        Row("🎌", "交叉旗/双旗", "jiaochaqi shuangqi"),
        Row("🏴", "黑旗", "heiqi"),
        Row("🏳️", "白旗/投降", "baiqi touxiang"),
        Row("🏳️‍🌈", "彩虹旗", "caihongqi"),
        Row("🏳️‍⚧️", "跨性别旗", "kuaxingbieqi"),
        Row("🏴‍☠️", "海盗旗/骷髅旗", "haidaoqi kulouqi"),
        Row("🇨🇳", "中国/五星红旗/中国国旗", "zhongguo wuxinghongqi zhongguoguoqi"),
        Row("🇭🇰", "香港", "xianggang"),
        Row("🇲🇴", "澳门", "aomen"),
        Row("🇹🇼", "台湾", "taiwan"),
        Row("🇺🇸", "美国", "meiguo"),
        Row("🇬🇧", "英国", "yingguo"),
        Row("🇯🇵", "日本", "riben"),
        Row("🇰🇷", "韩国", "hanguo"),
        Row("🇫🇷", "法国", "faguo"),
        Row("🇩🇪", "德国", "deguo"),
        Row("🇮🇹", "意大利", "yidali"),
        Row("🇪🇸", "西班牙", "xibanya"),
        Row("🇷🇺", "俄罗斯/俄国", "eluosi eguo"),
        Row("🇨🇦", "加拿大", "jianada"),
        Row("🇦🇺", "澳大利亚/澳洲", "aodaliya aozhou"),
        Row("🇧🇷", "巴西", "baxi"),
        Row("🇮🇳", "印度", "yindu"),
        Row("🇸🇬", "新加坡", "xinjiapo"),
        Row("🇲🇾", "马来西亚/大马", "malaixiya dama"),
        Row("🇹🇭", "泰国", "taiguo"),
        Row("🇻🇳", "越南", "yuenan"),
        Row("🇵🇭", "菲律宾", "feilvbin"),
        Row("🇮🇩", "印尼/印度尼西亚", "yinni yindunixiya"),
        Row("🇳🇱", "荷兰", "helan"),
        Row("🇨🇭", "瑞士", "ruishi"),
        Row("🇸🇪", "瑞典", "ruidian"),
        Row("🇳🇴", "挪威", "nuowei"),
        Row("🇩🇰", "丹麦", "danmai"),
        Row("🇫🇮", "芬兰", "fenlan"),
        Row("🇵🇹", "葡萄牙", "putaoya"),
        Row("🇬🇷", "希腊", "xila"),
        Row("🇹🇷", "土耳其", "tuerqi"),
        Row("🇵🇱", "波兰", "bolan"),
        Row("🇺🇦", "乌克兰", "wukelan"),
        Row("🇲🇽", "墨西哥", "moxige"),
        Row("🇦🇷", "阿根廷", "agenting"),
        Row("🇿🇦", "南非", "nanfei"),
        Row("🇪🇬", "埃及", "aiji"),
        Row("🇸🇦", "沙特/沙特阿拉伯", "shate shatealabo"),
        Row("🇦🇪", "阿联酋", "alianqiu"),
        Row("🇮🇱", "以色列", "yiselie"),
        Row("🇮🇷", "伊朗", "yilang"),
        Row("🇵🇰", "巴基斯坦", "bajisitan"),
        Row("🇧🇩", "孟加拉国/孟加拉", "mengjialaguo mengjiala"),
        Row("🇳🇿", "新西兰", "xinxilan"),
        Row("🇮🇪", "爱尔兰", "aierlan"),
        Row("🇧🇪", "比利时", "bilishi"),
        Row("🇦🇹", "奥地利", "aodili"),
        Row("🇨🇿", "捷克", "jieke"),
        Row("🇭🇺", "匈牙利", "xiongyali"),
        Row("🇷🇴", "罗马尼亚", "luomaniya"),
        Row("🇨🇱", "智利", "zhili"),
        Row("🇨🇴", "哥伦比亚", "gelunbiya"),
        Row("🇵🇪", "秘鲁", "bilu"),
        Row("🇻🇪", "委内瑞拉", "weineiruila"),
        Row("🇨🇺", "古巴", "guba"),
        Row("🇳🇬", "尼日利亚", "niriliya"),
        Row("🇰🇪", "肯尼亚", "kenniya"),
        Row("🇪🇹", "埃塞俄比亚", "aisaiebiya"),
        Row("🇲🇦", "摩洛哥", "moluoge"),
        Row("🇩🇿", "阿尔及利亚", "aerjiliya"),
        Row("🇶🇦", "卡塔尔", "kataer"),
        Row("🇰🇼", "科威特", "keweite"),
        Row("🇮🇶", "伊拉克", "yilake"),
        Row("🇱🇰", "斯里兰卡", "sililanka"),
        Row("🇳🇵", "尼泊尔", "niboer"),
        Row("🇰🇭", "柬埔寨", "jianpuzhai"),
        Row("🇲🇲", "缅甸", "miandian"),
        Row("🇧🇳", "文莱", "wenlai"),
    )

    private fun animal(): List<Row> = listOf(
        Row("🐶", "狗/小狗/狗头", "gou xiaogou goutou"),
        Row("🐱", "猫/猫咪/小猫", "mao maomi xiaomao"),
        Row("🐭", "老鼠/小老鼠", "laoshu xiaolaoshu"),
        Row("🐹", "仓鼠", "cangshu"),
        Row("🐰", "兔子/兔/小兔", "tuzi tu xiaotu"),
        Row("🦊", "狐狸", "huli"),
        Row("🐻", "熊/狗熊/小熊", "xiong gouxiong xiaoxiong"),
        Row("🐼", "熊猫/大熊猫", "xiongmao daxiongmao"),
        Row("🐻‍❄️", "北极熊/白熊", "beijixiong baixiong"),
        Row("🐨", "考拉/树袋熊/无尾熊", "kaola shudaixiong wuweixiong"),
        Row("🐯", "老虎/虎/虎头", "laohu hu hutou"),
        Row("🦁", "狮子", "shizi"),
        Row("🐮", "牛/牛头", "niu niutou"),
        Row("🐷", "猪/猪头/小猪", "zhu zhutou xiaozhu"),
        Row("🐽", "猪鼻子/猪鼻", "zhubizi zhubi"),
        Row("🐸", "青蛙", "qingwa"),
        Row("🐵", "猴子/猴/猴头", "houzi hou houtou"),
        Row("🙈", "捂眼猴/非礼勿视/捂眼睛", "wuyanhou feiliwushi wuyanjing"),
        Row("🙉", "捂耳猴/非礼勿听/捂耳朵", "wuerhou feiliwuting wuerduo"),
        Row("🙊", "捂嘴猴/非礼勿言/捂嘴", "wuzuihou feiliwuyan wuzui"),
        Row("🐒", "猴子/猴", "houzi hou"),
        Row("🐔", "鸡/母鸡", "ji muji"),
        Row("🐧", "企鹅", "qie"),
        Row("🐦", "鸟/小鸟", "niao xiaoniao"),
        Row("🐦‍⬛", "乌鸦/黑鸟", "wuya heiniao"),
        Row("🐤", "小鸡/小黄鸡", "xiaoji xiaohuangji"),
        Row("🐣", "破壳小鸡/破壳/孵化", "pokexiaoji poke fuhua"),
        Row("🐥", "小鸡/小鸡仔", "xiaoji xiaojizai"),
        Row("🦆", "鸭子/鸭", "yazi ya"),
        Row("🦅", "老鹰/鹰/雄鹰", "laoying ying xiongying"),
        Row("🦉", "猫头鹰", "maotouying"),
        Row("🦇", "蝙蝠", "bianfu"),
        Row("🐺", "狼/狼头/野狼", "lang langtou yelang"),
        Row("🐗", "野猪", "yezhu"),
        Row("🐴", "马/马头", "ma matou"),
        Row("🦄", "独角兽", "dujiaoshou"),
        Row("🐝", "蜜蜂/小蜜蜂", "mifeng xiaomifeng"),
        Row("🪱", "蚯蚓", "qiuyin"),
        Row("🐛", "毛毛虫/虫子/虫", "maomaochong chongzi chong"),
        Row("🦋", "蝴蝶", "hudie"),
        Row("🐌", "蜗牛", "woniu"),
        Row("🐞", "瓢虫/七星瓢虫", "piaochong qixingpiaochong"),
        Row("🐜", "蚂蚁", "mayi"),
        Row("🪰", "苍蝇", "cangying"),
        Row("🪲", "甲虫/甲壳虫", "jiachong jiaqiaochong"),
        Row("🪳", "蟑螂/小强", "zhanglang xiaoqiang"),
        Row("🦟", "蚊子", "wenzi"),
        Row("🦗", "蟋蟀/蛐蛐", "xishuai ququ"),
        Row("🕷️", "蜘蛛", "zhizhu"),
        Row("🕸️", "蜘蛛网/蛛网", "zhizhuwang zhuwang"),
        Row("🦂", "蝎子", "xiezi"),
        Row("🐢", "乌龟/龟/海龟", "wugui gui haigui"),
        Row("🐍", "蛇", "she"),
        Row("🦎", "蜥蜴/壁虎", "xiyi bihu"),
        Row("🦖", "霸王龙/恐龙/暴龙", "bawanglong konglong baolong"),
        Row("🦕", "恐龙/雷龙", "konglong leilong"),
        Row("🐙", "章鱼/八爪鱼", "zhangyu bazhuayu"),
        Row("🦑", "鱿鱼/乌贼/墨鱼", "youyu wuzei moyu"),
        Row("🦐", "虾/大虾", "xia daxia"),
        Row("🦞", "龙虾/小龙虾", "longxia xiaolongxia"),
        Row("🦀", "螃蟹/蟹", "pangxie xie"),
        Row("🪼", "水母/海蜇", "shuimu haizhe"),
        Row("🐡", "河豚", "hetun"),
        Row("🐠", "热带鱼", "redaiyu"),
        Row("🐟", "鱼/小鱼", "yu xiaoyu"),
        Row("🐬", "海豚", "haitun"),
        Row("🐳", "鲸鱼/喷水鲸", "jingyu penshuijing"),
        Row("🐋", "鲸鱼/蓝鲸/鲸", "jingyu lanjing jing"),
        Row("🦈", "鲨鱼/大白鲨", "shayu dabaisha"),
        Row("🦭", "海豹", "haibao"),
        Row("🐊", "鳄鱼", "eyu"),
        Row("🐅", "老虎/虎", "laohu hu"),
        Row("🐆", "豹子/猎豹/豹", "baozi liebao bao"),
        Row("🦓", "斑马", "banma"),
        Row("🦍", "大猩猩/金刚", "daxingxing jingang"),
        Row("🦧", "红毛猩猩", "hongmaoxingxing"),
        Row("🦣", "猛犸象/长毛象/猛犸", "mengmaxiang changmaoxiang mengma"),
        Row("🐘", "大象/象", "daxiang xiang"),
        Row("🦛", "河马", "hema"),
        Row("🦏", "犀牛", "xiniu"),
        Row("🐪", "骆驼/单峰驼", "luotuo danfengtuo"),
        Row("🐫", "骆驼/双峰驼", "luotuo shuangfengtuo"),
        Row("🦒", "长颈鹿", "changjinglu"),
        Row("🦘", "袋鼠", "daishu"),
        Row("🦬", "野牛/美洲野牛", "yeniu meizhouyeniu"),
        Row("🐃", "水牛", "shuiniu"),
        Row("🐂", "公牛/牛/黄牛", "gongniu niu huangniu"),
        Row("🐄", "奶牛/母牛", "nainiu muniu"),
        Row("🐎", "马/骏马", "ma junma"),
        Row("🐖", "猪/肥猪", "zhu feizhu"),
        Row("🐏", "公羊/羊", "gongyang yang"),
        Row("🐑", "绵羊/羊/小羊", "mianyang yang xiaoyang"),
        Row("🦙", "羊驼/草泥马/大羊驼", "yangtuo caonima dayangtuo"),
        Row("🐐", "山羊", "shanyang"),
        Row("🦌", "鹿/小鹿/梅花鹿", "lu xiaolu meihualu"),
        Row("🐕", "狗/小狗/狗狗", "gou xiaogou gougou"),
        Row("🐩", "贵宾犬/泰迪/贵妇犬", "guibinquan taidi guifuquan"),
        Row("🦮", "导盲犬", "daomangquan"),
        Row("🐕‍🦺", "服务犬/工作犬", "fuwuquan gongzuoquan"),
        Row("🐈", "猫/小猫", "mao xiaomao"),
        Row("🐈‍⬛", "黑猫", "heimao"),
        Row("🪶", "羽毛", "yumao"),
        Row("🐓", "公鸡/大公鸡", "gongji dagongji"),
        Row("🦃", "火鸡", "huoji"),
        Row("🦤", "渡渡鸟", "duduniao"),
        Row("🦚", "孔雀", "kongque"),
        Row("🦜", "鹦鹉", "yingwu"),
        Row("🦢", "天鹅", "tiane"),
        Row("🦩", "火烈鸟", "huolieniao"),
        Row("🕊️", "鸽子/和平鸽/白鸽", "gezi hepingge baige"),
        Row("🐇", "兔子/白兔/兔", "tuzi baitu tu"),
        Row("🦝", "浣熊/小浣熊", "huanxiong xiaohuanxiong"),
        Row("🦨", "臭鼬", "chouyou"),
        Row("🦡", "獾", "huan"),
        Row("🦫", "河狸/海狸", "heli haili"),
        Row("🦦", "水獭/海獭", "shuita haita"),
        Row("🦥", "树懒", "shulan"),
        Row("🐁", "小白鼠/白老鼠/小鼠", "xiaobaishu bailaoshu xiaoshu"),
        Row("🐀", "老鼠/耗子/大老鼠", "laoshu haozi dalaoshu"),
        Row("🐿️", "松鼠/花栗鼠", "songshu hualishu"),
        Row("🦔", "刺猬", "ciwei"),
        Row("🐾", "爪印/脚印/猫爪", "zhuayin jiaoyin maozhua"),
        Row("🐉", "龙/中国龙/神龙", "long zhongguolong shenlong"),
        Row("🐲", "龙头/龙", "longtou long"),
    )

    private fun plant(): List<Row> = listOf(
        Row("💐", "花束/一束花/捧花", "huashu yishuhua penghua"),
        Row("🌸", "樱花/桃花/花", "yinghua taohua hua"),
        Row("💮", "白花/小白花", "baihua xiaobaihua"),
        Row("🪷", "莲花/荷花", "lianhua hehua"),
        Row("🏵️", "花饰/玫瑰花结", "huashi meiguihuajie"),
        Row("🌹", "玫瑰/玫瑰花/红玫瑰", "meigui meiguihua hongmeigui"),
        Row("🥀", "凋谢/枯萎/枯萎玫瑰", "diaoxie kuwei kuweimeigui"),
        Row("🌺", "扶桑花/木槿花/大红花", "fusanghua mujinhua dahonghua"),
        Row("🌻", "向日葵/太阳花/葵花", "xiangrikui taiyanghua kuihua"),
        Row("🌼", "雏菊/小黄花/菊花", "chuju xiaohuanghua juhua"),
        Row("🌷", "郁金香", "yujinxiang"),
        Row("🪻", "风信子/薰衣草", "fengxinzi xunyicao"),
        Row("🌱", "幼苗/发芽/嫩芽", "youmiao faya nenya"),
        Row("🪴", "盆栽/盆景/绿植", "penzai penjing lvzhi"),
        Row("🌲", "松树/常青树", "songshu changqingshu"),
        Row("🌳", "树/大树/落叶树", "shu dashu luoyeshu"),
        Row("🌴", "椰子树/棕榈树/椰树", "yezishu zonglvshu yeshu"),
        Row("🌵", "仙人掌/仙人球", "xianrenzhang xianrenqiu"),
        Row("🌾", "水稻/稻穗/稻谷", "shuidao daosui daogu"),
        Row("🌿", "草药/绿叶/香草", "caoyao lvye xiangcao"),
        Row("☘️", "三叶草", "sanyecao"),
        Row("🍀", "四叶草/幸运草/幸运", "siyecao xingyuncao xingyun"),
        Row("🍁", "枫叶/红叶", "fengye hongye"),
        Row("🍂", "落叶/枯叶", "luoye kuye"),
        Row("🍃", "树叶/叶子", "shuye yezi"),
        Row("🪹", "空巢/空鸟窝", "kongchao kongniaowo"),
        Row("🪺", "鸟巢/鸟窝/鸟蛋", "niaochao niaowo niaodan"),
        Row("🍄", "蘑菇", "mogu"),
        Row("🐚", "贝壳/海螺", "beike hailuo"),
        Row("🪸", "珊瑚", "shanhu"),
        Row("🪨", "石头/岩石", "shitou yanshi"),
        Row("🌰", "栗子/板栗", "lizi banli"),
        Row("🌍", "地球/欧非地球", "diqiu oufeidiqiu"),
        Row("🌎", "地球/美洲地球", "diqiu meizhoudiqiu"),
        Row("🌏", "地球/亚洲地球", "diqiu yazhoudiqiu"),
        Row("🌐", "网络/互联网/经纬地球", "wangluo hulianwang jingweidiqiu"),
        Row("🪐", "土星", "tuxing"),
        Row("🌑", "新月/朔月", "xinyue shuoyue"),
        Row("🌒", "蛾眉月", "emeiyue"),
        Row("🌓", "上弦月", "shangxianyue"),
        Row("🌔", "盈凸月", "yingtuyue"),
        Row("🌕", "满月/圆月", "manyue yuanyue"),
        Row("🌖", "亏凸月", "kuituyue"),
        Row("🌗", "下弦月", "xiaxianyue"),
        Row("🌘", "残月", "canyue"),
        Row("🌙", "月亮/月牙/弯月", "yueliang yueya wanyue"),
        Row("🌚", "黑脸月亮/黑月亮", "heilianyueliang heiyueliang"),
        Row("🌛", "月亮脸/上弦月脸", "yuelianglian shangxianyuelian"),
        Row("🌜", "月亮脸/下弦月脸", "yuelianglian xiaxianyuelian"),
        Row("☀️", "太阳/晴天/晴", "taiyang qingtian qing"),
        Row("🌝", "满月脸/笑脸月亮", "manyuelian xiaolianyueliang"),
        Row("🌞", "太阳脸/笑脸太阳", "taiyanglian xiaoliantaiyang"),
        Row("⭐", "星星/五角星", "xingxing wujiaoxing"),
        Row("🌟", "闪亮星星/发光星星/星星", "shanliangxingxing faguangxingxing xingxing"),
        Row("🌠", "流星/许愿星", "liuxing xuyuanxing"),
        Row("☄️", "彗星/扫把星", "huixing saobaxing"),
        Row("🌌", "银河/星空/银河系", "yinhe xingkong yinhexi"),
        Row("⛅", "多云/晴转多云", "duoyun qingzhuanduoyun"),
        Row("⛈️", "雷阵雨/雷雨/暴风雨", "leizhenyu leiyu baofengyu"),
        Row("🌤️", "晴间多云/少云", "qingjianduoyun shaoyun"),
        Row("🌥️", "多云转阴/阴天", "duoyunzhuanyin yintian"),
        Row("🌦️", "太阳雨/阵雨", "taiyangyu zhenyu"),
        Row("🌧️", "下雨/雨/雨天/降雨", "xiayu yu yutian jiangyu"),
        Row("🌨️", "下雪/降雪", "xiaxue jiangxue"),
        Row("🌩️", "打雷/雷电/雷", "dalei leidian lei"),
        Row("🌪️", "龙卷风/旋风", "longjuanfeng xuanfeng"),
        Row("🌫️", "雾/大雾/雾霾", "wu dawu wumai"),
        Row("🌬️", "刮风/吹风/风", "guafeng chuifeng feng"),
        Row("🌈", "彩虹", "caihong"),
        Row("☂️", "雨伞/伞", "yusan san"),
        Row("☔", "雨伞/下雨/淋雨", "yusan xiayu linyu"),
        Row("⚡", "闪电/电", "shandian dian"),
        Row("❄️", "雪花/雪", "xuehua xue"),
        Row("☃️", "雪人", "xueren"),
        Row("⛄", "雪人/堆雪人", "xueren duixueren"),
        Row("🔥", "火/火焰/着火", "huo huoyan zhaohuo"),
        Row("💧", "水滴/水珠", "shuidi shuizhu"),
        Row("🌊", "海浪/浪花/波浪", "hailang langhua bolang"),
    )

    private fun food(): List<Row> = listOf(
        Row("🍇", "葡萄/提子", "putao tizi"),
        Row("🍈", "甜瓜/哈密瓜/香瓜", "tiangua hamigua xianggua"),
        Row("🍉", "西瓜", "xigua"),
        Row("🍊", "橘子/桔子/橙子", "juzi juzi chengzi"),
        Row("🍋", "柠檬", "ningmeng"),
        Row("🍋‍🟩", "青柠/青柠檬", "qingning qingningmeng"),
        Row("🍌", "香蕉", "xiangjiao"),
        Row("🍍", "菠萝/凤梨", "boluo fengli"),
        Row("🥭", "芒果", "mangguo"),
        Row("🍎", "苹果/红苹果", "pingguo hongpingguo"),
        Row("🍏", "青苹果", "qingpingguo"),
        Row("🍐", "梨/梨子/鸭梨", "li lizi yali"),
        Row("🍑", "桃子/蜜桃/桃", "taozi mitao tao"),
        Row("🍒", "樱桃/车厘子", "yingtao chelizi"),
        Row("🍓", "草莓", "caomei"),
        Row("🫐", "蓝莓", "lanmei"),
        Row("🥝", "猕猴桃/奇异果", "mihoutao qiyiguo"),
        Row("🍅", "西红柿/番茄", "xihongshi fanqie"),
        Row("🫒", "橄榄", "ganlan"),
        Row("🥥", "椰子", "yezi"),
        Row("🥑", "牛油果/鳄梨", "niuyouguo eli"),
        Row("🍆", "茄子", "qiezi"),
        Row("🥔", "土豆/马铃薯/洋芋", "tudou malingshu yangyu"),
        Row("🥕", "胡萝卜/红萝卜", "huluobo hongluobo"),
        Row("🌽", "玉米/苞米", "yumi baomi"),
        Row("🌶️", "辣椒/红辣椒", "lajiao honglajiao"),
        Row("🫑", "青椒/甜椒/柿子椒", "qingjiao tianjiao shizijiao"),
        Row("🥒", "黄瓜/青瓜", "huanggua qinggua"),
        Row("🥬", "白菜/青菜/生菜/蔬菜", "baicai qingcai shengcai shucai"),
        Row("🥦", "西兰花/花椰菜", "xilanhua huayecai"),
        Row("🧄", "大蒜/蒜/蒜头", "dasuan suan suantou"),
        Row("🧅", "洋葱", "yangcong"),
        Row("🥜", "花生/花生米", "huasheng huashengmi"),
        Row("🫘", "豆子/红豆/豆", "douzi hongdou dou"),
        Row("🫚", "生姜/姜", "shengjiang jiang"),
        Row("🫛", "豌豆/豆荚", "wandou doujia"),
        Row("🍞", "面包/吐司", "mianbao tusi"),
        Row("🥐", "牛角包/可颂/羊角面包", "niujiaobao kesong yangjiaomianbao"),
        Row("🥖", "法棍/法棍面包", "fagun fagunmianbao"),
        Row("🫓", "大饼/烙饼/馕", "dabing laobing nang"),
        Row("🥨", "椒盐卷饼/蝴蝶饼", "jiaoyanjuanbing hudiebing"),
        Row("🥯", "贝果/百吉饼", "beiguo baijibing"),
        Row("🥞", "松饼/煎饼", "songbing jianbing"),
        Row("🧇", "华夫饼", "huafubing"),
        Row("🧀", "奶酪/芝士/起司", "nailao zhishi qisi"),
        Row("🍖", "肉/骨头肉", "rou gutourou"),
        Row("🍗", "鸡腿/炸鸡", "jitui zhaji"),
        Row("🥩", "牛排/生肉/肉排", "niupai shengrou roupai"),
        Row("🥓", "培根", "peigen"),
        Row("🍔", "汉堡/汉堡包", "hanbao hanbaobao"),
        Row("🍟", "薯条", "shutiao"),
        Row("🍕", "披萨/比萨", "pisa bisa"),
        Row("🌭", "热狗", "regou"),
        Row("🥪", "三明治", "sanmingzhi"),
        Row("🌮", "塔可/墨西哥玉米饼", "take moxigeyumibing"),
        Row("🌯", "墨西哥卷饼/卷饼", "moxigejuanbing juanbing"),
        Row("🫔", "墨西哥粽子/玉米粽", "moxigezongzi yumizong"),
        Row("🥙", "皮塔饼/口袋饼", "pitabing koudaibing"),
        Row("🧆", "炸豆丸子/法拉费", "zhadouwanzi falafei"),
        Row("🥚", "鸡蛋/蛋", "jidan dan"),
        Row("🍳", "煎蛋/荷包蛋/煎鸡蛋", "jiandan hebaodan jianjidan"),
        Row("🥘", "海鲜饭/西班牙海鲜饭", "haixianfan xibanyahaixianfan"),
        Row("🍲", "火锅/炖菜/煲汤", "huoguo duncai baotang"),
        Row("🫕", "芝士火锅/奶酪火锅", "zhishihuoguo nailaohuoguo"),
        Row("🥣", "麦片/碗/粥", "maipian wan zhou"),
        Row("🥗", "沙拉/色拉/蔬菜沙拉", "shala sela shucaishala"),
        Row("🍿", "爆米花", "baomihua"),
        Row("🧈", "黄油/奶油/牛油", "huangyou naiyou niuyou"),
        Row("🧂", "盐/食盐", "yan shiyan"),
        Row("🥫", "罐头", "guantou"),
        Row("🍱", "便当/盒饭", "biandang hefan"),
        Row("🍘", "仙贝/米饼", "xianbei mibing"),
        Row("🍙", "饭团", "fantuan"),
        Row("🍚", "米饭/白饭/饭", "mifan baifan fan"),
        Row("🍛", "咖喱饭/咖喱", "galifan gali"),
        Row("🍜", "拉面/面条/泡面/汤面", "lamian miantiao paomian tangmian"),
        Row("🍝", "意大利面/意面/意粉", "yidalimian yimian yifen"),
        Row("🍠", "红薯/烤红薯/地瓜/番薯", "hongshu kaohongshu digua fanshu"),
        Row("🍢", "关东煮/串串", "guandongzhu chuanchuan"),
        Row("🍣", "寿司", "shousi"),
        Row("🍤", "炸虾/天妇罗", "zhaxia tianfuluo"),
        Row("🍥", "鱼板/鸣门卷/鱼糕", "yuban mingmenjuan yugao"),
        Row("🥮", "月饼", "yuebing"),
        Row("🍡", "团子/丸子/糯米团子", "tuanzi wanzi nuomituanzi"),
        Row("🥟", "饺子/水饺", "jiaozi shuijiao"),
        Row("🥠", "幸运饼干/签语饼", "xingyunbinggan qianyubing"),
        Row("🥡", "外卖盒/打包盒/外卖", "waimaihe dabaohe waimai"),
        Row("🦪", "生蚝/牡蛎/蚝", "shenghao muli hao"),
        Row("🍦", "冰淇淋/甜筒/冰激凌", "bingqilin tiantong bingjiling"),
        Row("🍧", "刨冰/沙冰", "baobing shabing"),
        Row("🍨", "冰激凌/圣代", "bingjiling shengdai"),
        Row("🍩", "甜甜圈/面包圈", "tiantianquan mianbaoquan"),
        Row("🍪", "饼干/曲奇", "binggan quqi"),
        Row("🎂", "生日蛋糕/蛋糕/生日", "shengridangao dangao shengri"),
        Row("🍰", "蛋糕/奶油蛋糕/切块蛋糕", "dangao naiyoudangao qiekuaidangao"),
        Row("🧁", "纸杯蛋糕/杯子蛋糕/马芬", "zhibeidangao beizidangao mafen"),
        Row("🥧", "派/馅饼/苹果派", "pai xianbing pingguopai"),
        Row("🍫", "巧克力/朱古力", "qiaokeli zhuguli"),
        Row("🍬", "糖果/糖", "tangguo tang"),
        Row("🍭", "棒棒糖", "bangbangtang"),
        Row("🍮", "布丁", "buding"),
        Row("🍯", "蜂蜜/蜜罐/蜜糖", "fengmi miguan mitang"),
        Row("🍼", "奶瓶", "naiping"),
        Row("🥛", "牛奶/奶", "niunai nai"),
        Row("☕", "咖啡", "kafei"),
        Row("🫖", "茶壶", "chahu"),
        Row("🍵", "茶/绿茶/茶杯", "cha lvcha chabei"),
        Row("🍶", "清酒/日本酒", "qingjiu ribenjiu"),
        Row("🍾", "香槟/香槟酒/开香槟", "xiangbin xiangbinjiu kaixiangbin"),
        Row("🍷", "红酒/葡萄酒", "hongjiu putaojiu"),
        Row("🍸", "鸡尾酒/马天尼", "jiweijiu matianni"),
        Row("🍹", "果汁/热带鸡尾酒", "guozhi redaijiweijiu"),
        Row("🍺", "啤酒", "pijiu"),
        Row("🍻", "干杯/碰杯", "ganbei pengbei"),
        Row("🥂", "碰杯/干杯/香槟杯", "pengbei ganbei xiangbinbei"),
        Row("🥃", "威士忌/洋酒", "weishiji yangjiu"),
        Row("🫗", "倒水/倒酒", "daoshui daojiu"),
        Row("🥤", "饮料/可乐/汽水", "yinliao kele qishui"),
        Row("🧋", "奶茶/珍珠奶茶", "naicha zhenzhunaicha"),
        Row("🧃", "果汁盒/盒装果汁/果汁", "guozhihe hezhuangguozhi guozhi"),
        Row("🧉", "马黛茶", "madaicha"),
        Row("🧊", "冰块/冰", "bingkuai bing"),
        Row("🥢", "筷子", "kuaizi"),
        Row("🍽️", "餐盘/餐具/吃饭", "canpan canju chifan"),
        Row("🍴", "刀叉/餐具", "daocha canju"),
        Row("🥄", "勺子/汤匙/调羹", "shaozi tangchi tiaogeng"),
    )

    private fun travel(): List<Row> = listOf(
        Row("🚗", "小汽车/汽车/轿车", "xiaoqiche qiche jiaoche"),
        Row("🚕", "出租车/的士/打车", "chuzuche dishi dache"),
        Row("🚙", "越野车/吉普车", "yueyeche jipuche"),
        Row("🚌", "公交车/巴士/大巴", "gongjiaoche bashi daba"),
        Row("🚎", "无轨电车/电车", "wuguidianche dianche"),
        Row("🏎️", "赛车/跑车", "saiche paoche"),
        Row("🚓", "警车", "jingche"),
        Row("🚑", "救护车", "jiuhuche"),
        Row("🚒", "消防车", "xiaofangche"),
        Row("🚐", "面包车/小巴", "mianbaoche xiaoba"),
        Row("🛻", "皮卡/皮卡车", "pika pikache"),
        Row("🚚", "货车/卡车/送货车", "huoche kache songhuoche"),
        Row("🚛", "大货车/半挂车/大卡车", "dahuoche banguache dakache"),
        Row("🚜", "拖拉机", "tuolaji"),
        Row("🦯", "盲杖/导盲杖/拐杖", "mangzhang daomangzhang guaizhang"),
        Row("🦽", "轮椅/手动轮椅", "lunyi shoudonglunyi"),
        Row("🦼", "电动轮椅", "diandonglunyi"),
        Row("🛴", "滑板车", "huabanche"),
        Row("🚲", "自行车/单车/脚踏车", "zixingche danche jiaotache"),
        Row("🛵", "电动车/小摩托/踏板车/电瓶车", "diandongche xiaomotuo tabanche dianpingche"),
        Row("🏍️", "摩托车/机车", "motuoche jiche"),
        Row("🛺", "三轮车/嘟嘟车", "sanlunche duduche"),
        Row("🚨", "警灯/警报/报警", "jingdeng jingbao baojing"),
        Row("🚔", "警车/迎面警车", "jingche yingmianjingche"),
        Row("🚍", "公交车/迎面公交车", "gongjiaoche yingmiangongjiaoche"),
        Row("🚘", "汽车/迎面汽车", "qiche yingmianqiche"),
        Row("🚖", "出租车/迎面出租车", "chuzuche yingmianchuzuche"),
        Row("🚡", "缆车/空中缆车", "lanche kongzhonglanche"),
        Row("🚠", "索道/登山缆车", "suodao dengshanlanche"),
        Row("🚟", "悬挂列车/空轨", "xuangualieche konggui"),
        Row("🚃", "车厢/火车车厢", "chexiang huochechexiang"),
        Row("🚋", "电车/有轨电车/叮叮车", "dianche youguidianche dingdingche"),
        Row("🚞", "登山火车/山地火车", "dengshanhuoche shandihuoche"),
        Row("🚝", "单轨列车/磁悬浮", "danguilieche cixuanfu"),
        Row("🚄", "高铁/高速列车", "gaotie gaosulieche"),
        Row("🚅", "动车/高铁/子弹头列车", "dongche gaotie zidantoulieche"),
        Row("🚈", "轻轨", "qinggui"),
        Row("🚂", "火车头/蒸汽火车/小火车", "huochetou zhengqihuoche xiaohuoche"),
        Row("🚆", "火车/列车", "huoche lieche"),
        Row("🚇", "地铁", "ditie"),
        Row("🚊", "电车/有轨电车", "dianche youguidianche"),
        Row("🚉", "车站/火车站", "chezhan huochezhan"),
        Row("✈️", "飞机/客机", "feiji keji"),
        Row("🛫", "起飞/飞机起飞/出发", "qifei feijiqifei chufa"),
        Row("🛬", "降落/飞机降落", "jiangluo feijijiangluo"),
        Row("🛩️", "小飞机/私人飞机", "xiaofeiji sirenfeiji"),
        Row("💺", "座位/座椅", "zuowei zuoyi"),
        Row("🛰️", "卫星/人造卫星", "weixing renzaoweixing"),
        Row("🚀", "火箭/发射", "huojian fashe"),
        Row("🛸", "飞碟/不明飞行物", "feidie bumingfeixingwu"),
        Row("🚁", "直升机/直升飞机", "zhishengji zhishengfeiji"),
        Row("🛶", "独木舟/皮划艇", "dumuzhou pihuating"),
        Row("⛵", "帆船/一帆风顺", "fanchuan yifanfengshun"),
        Row("🚤", "快艇/摩托艇", "kuaiting motuoting"),
        Row("🛥️", "游艇", "youting"),
        Row("🛳️", "游轮/邮轮/客轮", "youlun youlun kelun"),
        Row("⛴️", "渡轮/轮渡/渡船", "dulun lundu duchuan"),
        Row("🚢", "轮船/船/大船", "lunchuan chuan dachuan"),
        Row("⚓", "锚/船锚", "mao chuanmao"),
        Row("🪝", "钩子/挂钩", "gouzi guagou"),
        Row("⛽", "加油站/加油", "jiayouzhan jiayou"),
        Row("🚧", "施工/路障/施工中", "shigong luzhang shigongzhong"),
        Row("🚦", "红绿灯/交通灯/信号灯", "honglvdeng jiaotongdeng xinhaodeng"),
        Row("🚥", "横向红绿灯/红绿灯", "hengxianghonglvdeng honglvdeng"),
        Row("🚏", "公交站/站牌/公交站牌", "gongjiaozhan zhanpai gongjiaozhanpai"),
        Row("🗺️", "地图/世界地图", "ditu shijieditu"),
        Row("🗿", "石像/摩艾/摩艾石像", "shixiang moai moaishixiang"),
        Row("🗽", "自由女神/自由女神像", "ziyounvshen ziyounvshenxiang"),
        Row("🗼", "铁塔/东京塔/东京铁塔", "tieta dongjingta dongjingtieta"),
        Row("🏰", "城堡", "chengbao"),
        Row("🏯", "日本城堡/日式城堡/天守阁", "ribenchengbao rishichengbao tianshouge"),
        Row("🏟️", "体育场/体育馆", "tiyuchang tiyuguan"),
        Row("🎡", "摩天轮/游乐园", "motianlun youleyuan"),
        Row("🎢", "过山车", "guoshanche"),
        Row("🎠", "旋转木马/木马", "xuanzhuanmuma muma"),
        Row("⛲", "喷泉", "penquan"),
        Row("⛱️", "遮阳伞/沙滩伞/太阳伞", "zheyangsan shatansan taiyangsan"),
        Row("🏖️", "沙滩/海滩/海边", "shatan haitan haibian"),
        Row("🏝️", "海岛/小岛/荒岛", "haidao xiaodao huangdao"),
        Row("🏜️", "沙漠", "shamo"),
        Row("🌋", "火山/火山爆发", "huoshan huoshanbaofa"),
        Row("⛰️", "山/高山/爬山", "shan gaoshan pashan"),
        Row("🏔️", "雪山", "xueshan"),
        Row("🗻", "富士山", "fushishan"),
        Row("🏕️", "露营/野营", "luying yeying"),
        Row("⛺", "帐篷", "zhangpeng"),
        Row("🛖", "茅草屋/小屋/草屋", "maocaowu xiaowu caowu"),
        Row("🏠", "房子/家/房屋", "fangzi jia fangwu"),
        Row("🏡", "别墅/花园房子", "bieshu huayuanfangzi"),
        Row("🏘️", "小区/住宅区", "xiaoqu zhuzhaiqu"),
        Row("🏚️", "破房子/废弃房屋/老房子", "pofangzi feiqifangwu laofangzi"),
        Row("🏗️", "工地/塔吊/建筑工地", "gongdi tadiao jianzhugongdi"),
        Row("🏭", "工厂", "gongchang"),
        Row("🏢", "办公楼/大厦/写字楼/公司", "bangonglou dasha xiezilou gongsi"),
        Row("🏬", "商场/百货商场", "shangchang baihuoshangchang"),
        Row("🏣", "日本邮局/邮局", "ribenyouju youju"),
        Row("🏤", "邮局", "youju"),
        Row("🏥", "医院", "yiyuan"),
        Row("🏦", "银行", "yinhang"),
        Row("🏨", "酒店/宾馆/旅馆", "jiudian binguan lvguan"),
        Row("🏪", "便利店/超市/小卖部", "bianlidian chaoshi xiaomaibu"),
        Row("🏫", "学校", "xuexiao"),
        Row("🏩", "情侣酒店/爱情旅馆", "qinglvjiudian aiqinglvguan"),
        Row("💒", "婚礼/结婚/婚礼教堂", "hunli jiehun hunlijiaotang"),
        Row("🏛️", "博物馆/古典建筑", "bowuguan gudianjianzhu"),
        Row("⛪", "教堂", "jiaotang"),
        Row("🕌", "清真寺", "qingzhensi"),
        Row("🕍", "犹太教堂/犹太会堂", "youtaijiaotang youtaihuitang"),
        Row("🛕", "印度神庙/寺庙", "yindushenmiao simiao"),
        Row("🕋", "天房/克尔白/麦加", "tianfang keerbai maijia"),
        Row("⛩️", "神社/鸟居", "shenshe niaoju"),
        Row("🛤️", "铁轨/铁路/铁道", "tiegui tielu tiedao"),
        Row("🛣️", "公路/高速公路/马路", "gonglu gaosugonglu malu"),
        Row("🗾", "日本地图", "ribenditu"),
        Row("🎑", "赏月/中秋赏月", "shangyue zhongqiushangyue"),
        Row("🏞️", "国家公园/风景/山水", "guojiagongyuan fengjing shanshui"),
        Row("🌅", "日出/海上日出/朝阳", "richu haishangrichu zhaoyang"),
        Row("🌄", "山间日出/日出", "shanjianrichu richu"),
        Row("🎇", "仙女棒/烟火/小烟花", "xiannvbang yanhuo xiaoyanhua"),
        Row("🎆", "烟花/焰火/放烟花", "yanhua yanhuo fangyanhua"),
        Row("🌇", "日落/夕阳/落日", "riluo xiyang luori"),
        Row("🌆", "黄昏/傍晚/城市黄昏", "huanghun bangwan chengshihuanghun"),
        Row("🏙️", "城市/都市/高楼大厦", "chengshi dushi gaoloudasha"),
        Row("🌃", "夜景/夜晚/城市夜景", "yejing yewan chengshiyejing"),
        Row("🌉", "大桥/桥/跨海大桥", "daqiao qiao kuahaidaqiao"),
        Row("🌁", "大雾/雾/雾天", "dawu wu wutian"),
    )

    private fun activity(): List<Row> = listOf(
        Row("⚽", "足球", "zuqiu"),
        Row("🏀", "篮球", "lanqiu"),
        Row("🏈", "橄榄球/美式橄榄球", "ganlanqiu meishiganlanqiu"),
        Row("⚾", "棒球", "bangqiu"),
        Row("🥎", "垒球", "leiqiu"),
        Row("🎾", "网球", "wangqiu"),
        Row("🏐", "排球", "paiqiu"),
        Row("🏉", "英式橄榄球/橄榄球", "yingshiganlanqiu ganlanqiu"),
        Row("🥏", "飞盘", "feipan"),
        Row("🎱", "台球/桌球/黑八", "taiqiu zhuoqiu heiba"),
        Row("🪀", "悠悠球/溜溜球", "youyouqiu liuliuqiu"),
        Row("🏓", "乒乓球", "pingpangqiu"),
        Row("🏸", "羽毛球", "yumaoqiu"),
        Row("🏒", "冰球", "bingqiu"),
        Row("🏑", "曲棍球", "qugunqiu"),
        Row("🥍", "长曲棍球", "changqugunqiu"),
        Row("🏏", "板球", "banqiu"),
        Row("🪃", "回旋镖", "huixuanbiao"),
        Row("🥅", "球门", "qiumen"),
        Row("⛳", "高尔夫/高尔夫球", "gaoerfu gaoerfuqiu"),
        Row("🪁", "风筝", "fengzheng"),
        Row("🏹", "弓箭/射箭", "gongjian shejian"),
        Row("🎣", "钓鱼/鱼竿", "diaoyu yugan"),
        Row("🤿", "潜水镜/潜水", "qianshuijing qianshui"),
        Row("🥊", "拳击/拳击手套", "quanji quanjishoutao"),
        Row("🥋", "柔道服/道服", "roudaofu daofu"),
        Row("🎽", "运动背心/背心", "yundongbeixin beixin"),
        Row("🛹", "滑板", "huaban"),
        Row("🛼", "轮滑鞋/旱冰鞋", "lunhuaxie hanbingxie"),
        Row("🛷", "雪橇", "xueqiao"),
        Row("⛸️", "溜冰鞋/冰刀/滑冰", "liubingxie bingdao huabing"),
        Row("🥌", "冰壶", "binghu"),
        Row("🎿", "滑雪板/雪板", "huaxueban xueban"),
        Row("⛷️", "滑雪/滑雪者/双板滑雪", "huaxue huaxuezhe shuangbanhuaxue"),
        Row("🏂", "单板滑雪", "danbanhuaxue"),
        Row("🪂", "降落伞/跳伞", "jiangluosan tiaosan"),
        Row("🏋️", "举重/健身/撸铁", "juzhong jianshen lutie"),
        Row("🤼", "摔跤", "shuaijiao"),
        Row("🤸", "侧手翻/体操", "ceshoufan ticao"),
        Row("⛹️", "打篮球/运球", "dalanqiu yunqiu"),
        Row("🤺", "击剑", "jijian"),
        Row("🤾", "手球", "shouqiu"),
        Row("🏌️", "打高尔夫", "dagaoerfu"),
        Row("🏇", "赛马/骑马", "saima qima"),
        Row("🧘", "瑜伽/打坐/冥想", "yujia dazuo mingxiang"),
        Row("🏄", "冲浪", "chonglang"),
        Row("🏊", "游泳", "youyong"),
        Row("🤽", "水球", "shuiqiu"),
        Row("🚣", "划船", "huachuan"),
        Row("🚵", "山地车/山地自行车", "shandiche shandizixingche"),
        Row("🚴", "骑自行车/骑车", "qizixingche qiche"),
        Row("🏆", "奖杯/冠军", "jiangbei guanjun"),
        Row("🥇", "金牌/第一名", "jinpai diyiming"),
        Row("🥈", "银牌/第二名", "yinpai dierming"),
        Row("🥉", "铜牌/第三名", "tongpai disanming"),
        Row("🏅", "奖牌", "jiangpai"),
        Row("🎖️", "勋章/军功章", "xunzhang jungongzhang"),
        Row("🎗️", "丝带/提醒丝带", "sidai tixingsidai"),
        Row("🎫", "票/门票/车票", "piao menpiao chepiao"),
        Row("🎟️", "入场券/门票", "ruchangquan menpiao"),
        Row("🎪", "马戏团", "maxituan"),
        Row("🤹", "杂耍/杂技", "zashua zaji"),
        Row("🎭", "面具/戏剧/表演", "mianju xiju biaoyan"),
        Row("🩰", "芭蕾舞鞋/芭蕾/舞鞋", "baleiwuxie balei wuxie"),
        Row("🎨", "调色板/画画/美术", "tiaoseban huahua meishu"),
        Row("🎬", "场记板/电影/拍戏", "changjiban dianying paixi"),
        Row("🎤", "麦克风/话筒/唱歌", "maikefeng huatong changge"),
        Row("🎧", "耳机", "erji"),
        Row("🎼", "乐谱/五线谱", "yuepu wuxianpu"),
        Row("🎹", "钢琴/琴键", "gangqin qinjian"),
        Row("🥁", "鼓/架子鼓/打鼓", "gu jiazigu dagu"),
        Row("🪘", "非洲鼓/长鼓/手鼓", "feizhougu changgu shougu"),
        Row("🪇", "沙锤/沙球", "shachui shaqiu"),
        Row("🎷", "萨克斯/萨克斯风", "sakesi sakesifeng"),
        Row("🎺", "小号/喇叭", "xiaohao laba"),
        Row("🪗", "手风琴", "shoufengqin"),
        Row("🎸", "吉他/电吉他", "jita dianjita"),
        Row("🪕", "班卓琴", "banzhuoqin"),
        Row("🎻", "小提琴", "xiaotiqin"),
        Row("🪈", "笛子/长笛", "dizi changdi"),
        Row("🎲", "骰子/色子", "touzi shaizi"),
        Row("♟️", "国际象棋/象棋/棋子", "guojixiangqi xiangqi qizi"),
        Row("🎯", "飞镖/靶心/命中", "feibiao baxin mingzhong"),
        Row("🎳", "保龄球", "baolingqiu"),
        Row("🎮", "游戏手柄/手柄/打游戏/游戏机", "youxishoubing shoubing dayouxi youxiji"),
        Row("🎰", "老虎机/赌博机", "laohuji duboji"),
        Row("🧩", "拼图", "pintu"),
    )

    private fun objects(): List<Row> = listOf(
        Row("⌚", "手表/腕表", "shoubiao wanbiao"),
        Row("📱", "手机", "shouji"),
        Row("📲", "来电/手机接收", "laidian shoujijieshou"),
        Row("💻", "电脑/笔记本电脑/笔记本", "diannao bijibendiannao bijiben"),
        Row("⌨️", "键盘", "jianpan"),
        Row("🖥️", "台式电脑/显示器", "taishidiannao xianshiqi"),
        Row("🖨️", "打印机", "dayinji"),
        Row("🖱️", "鼠标", "shubiao"),
        Row("🖲️", "轨迹球", "guijiqiu"),
        Row("🕹️", "摇杆/游戏摇杆", "yaogan youxiyaogan"),
        Row("🗜️", "夹钳/压缩/台钳", "jiaqian yasuo taiqian"),
        Row("💽", "磁盘/迷你光盘", "cipan miniguangpan"),
        Row("💾", "软盘", "ruanpan"),
        Row("💿", "光盘/光碟", "guangpan guangdie"),
        Row("📀", "影碟", "yingdie"),
        Row("📼", "录像带/磁带", "luxiangdai cidai"),
        Row("📷", "相机/照相机", "xiangji zhaoxiangji"),
        Row("📸", "拍照/闪光灯", "paizhao shanguangdeng"),
        Row("📹", "摄像机/录像机", "shexiangji luxiangji"),
        Row("🎥", "摄影机/电影摄影机", "sheyingji dianyingsheyingji"),
        Row("📽️", "放映机/投影仪", "fangyingji touyingyi"),
        Row("🎞️", "胶片/胶卷", "jiaopian jiaojuan"),
        Row("📞", "电话/听筒", "dianhua tingtong"),
        Row("☎️", "电话/座机/电话机", "dianhua zuoji dianhuaji"),
        Row("📟", "传呼机/寻呼机", "chuanhuji xunhuji"),
        Row("📠", "传真机/传真", "chuanzhenji chuanzhen"),
        Row("📺", "电视/电视机", "dianshi dianshiji"),
        Row("📻", "收音机/广播", "shouyinji guangbo"),
        Row("🎙️", "麦克风/话筒/录音", "maikefeng huatong luyin"),
        Row("🎚️", "音量滑块/滑块", "yinlianghuakuai huakuai"),
        Row("🎛️", "旋钮/调音台/控制旋钮", "xuanniu tiaoyintai kongzhixuanniu"),
        Row("🧭", "指南针/罗盘", "zhinanzhen luopan"),
        Row("⏱️", "秒表/计时器", "miaobiao jishiqi"),
        Row("⏲️", "定时器/计时器", "dingshiqi jishiqi"),
        Row("⏰", "闹钟", "naozhong"),
        Row("🕰️", "座钟/时钟", "zuozhong shizhong"),
        Row("⌛", "沙漏", "shalou"),
        Row("⏳", "沙漏/倒计时", "shalou daojishi"),
        Row("📡", "卫星天线/雷达/天线", "weixingtianxian leida tianxian"),
        Row("🔋", "电池", "dianchi"),
        Row("🪫", "低电量/没电", "didianliang meidian"),
        Row("🔌", "插头/电源插头", "chatou dianyuanchatou"),
        Row("💡", "灯泡/电灯泡", "dengpao diandengpao"),
        Row("🔦", "手电筒/手电", "shoudiantong shoudian"),
        Row("🕯️", "蜡烛", "lazhu"),
        Row("🪔", "油灯/酥油灯", "youdeng suyoudeng"),
        Row("🧯", "灭火器", "miehuoqi"),
        Row("🛢️", "油桶/汽油桶", "youtong qiyoutong"),
        Row("💸", "花钱/飞钱/撒钱", "huaqian feiqian saqian"),
        Row("💵", "美元/美金/钞票", "meiyuan meijin chaopiao"),
        Row("💴", "日元", "riyuan"),
        Row("💶", "欧元", "ouyuan"),
        Row("💷", "英镑", "yingbang"),
        Row("🪙", "硬币/金币", "yingbi jinbi"),
        Row("💰", "钱袋/钱/发财", "qiandai qian facai"),
        Row("💳", "银行卡/信用卡", "yinhangka xinyongka"),
        Row("🪪", "身份证/证件", "shenfenzheng zhengjian"),
        Row("💎", "钻石/宝石", "zuanshi baoshi"),
        Row("⚖️", "天平/秤", "tianping cheng"),
        Row("🪜", "梯子", "tizi"),
        Row("🧰", "工具箱", "gongjuxiang"),
        Row("🪛", "螺丝刀/改锥", "luosidao gaizhui"),
        Row("🔧", "扳手", "banshou"),
        Row("🔨", "锤子/榔头", "chuizi langtou"),
        Row("⚒️", "锤子和镐/双锤", "chuizihegao shuangchui"),
        Row("🛠️", "工具/维修/锤子扳手", "gongju weixiu chuizibanshou"),
        Row("⛏️", "镐/十字镐/矿镐", "gao shizigao kuanggao"),
        Row("🪚", "锯子/锯", "juzi ju"),
        Row("🔩", "螺丝/螺栓/螺丝钉", "luosi luoshuan luosiding"),
        Row("⚙️", "齿轮/设置", "chilun shezhi"),
        Row("🪤", "捕鼠器/老鼠夹", "bushuqi laoshujia"),
        Row("🧱", "砖头/砖/搬砖", "zhuantou zhuan banzhuan"),
        Row("⛓️", "链条/锁链/铁链", "liantiao suolian tielian"),
        Row("🧲", "磁铁/吸铁石", "citie xitieshi"),
        Row("🔫", "手枪/水枪/枪", "shouqiang shuiqiang qiang"),
        Row("💣", "炸弹", "zhadan"),
        Row("🧨", "鞭炮/爆竹/炮仗", "bianpao baozhu paozhang"),
        Row("🪓", "斧头/斧子", "futou fuzi"),
        Row("🔪", "菜刀/刀", "caidao dao"),
        Row("🗡️", "匕首/短剑", "bishou duanjian"),
        Row("⚔️", "双剑/交叉剑", "shuangjian jiaochajian"),
        Row("🛡️", "盾牌/盾", "dunpai dun"),
        Row("🚬", "香烟/烟/抽烟", "xiangyan yan chouyan"),
        Row("⚰️", "棺材", "guancai"),
        Row("🪦", "墓碑/坟墓", "mubei fenmu"),
        Row("⚱️", "骨灰盒/骨灰坛", "guhuihe guhuitan"),
        Row("🏺", "陶罐/双耳瓶/花瓶", "taoguan shuangerping huaping"),
        Row("🔮", "水晶球/占卜", "shuijingqiu zhanbu"),
        Row("📿", "佛珠/念珠", "fozhu nianzhu"),
        Row("🧿", "蓝眼睛/邪眼/护身符", "lanyanjing xieyan hushenfu"),
        Row("🪬", "法蒂玛之手/护身符", "fadimazhishou hushenfu"),
        Row("💈", "理发店/理发灯", "lifadian lifadeng"),
        Row("⚗️", "蒸馏器/蒸馏瓶", "zhengliuqi zhengliuping"),
        Row("🔭", "望远镜/天文望远镜", "wangyuanjing tianwenwangyuanjing"),
        Row("🔬", "显微镜", "xianweijing"),
        Row("🕳️", "洞/坑", "dong keng"),
        Row("🩹", "创可贴/创口贴", "chuangketie chuangkoutie"),
        Row("🩺", "听诊器", "tingzhenqi"),
        Row("🩻", "胸片/透视/拍片", "xiongpian toushi paipian"),
        Row("💊", "药丸/药/胶囊", "yaowan yao jiaonang"),
        Row("💉", "注射器/打针/针筒", "zhusheqi dazhen zhentong"),
        Row("🩸", "血滴/血/献血/献血", "xuedi xue xianxue xianxie"),
        Row("🧬", "基因/脱氧核糖核酸", "jiyin tuoyanghetanghesuan"),
        Row("🦠", "病毒/细菌/微生物", "bingdu xijun weishengwu"),
        Row("🧫", "培养皿", "peiyangmin"),
        Row("🧪", "试管/实验", "shiguan shiyan"),
        Row("🌡️", "温度计/体温计", "wenduji tiwenji"),
        Row("🧹", "扫把/扫帚/笤帚", "saoba saozhou tiaozhou"),
        Row("🪠", "马桶塞/皮搋子/马桶吸", "matongsai pichuaizi matongxi"),
        Row("🧺", "篮子/洗衣篮", "lanzi xiyilan"),
        Row("🧻", "卫生纸/卷纸/厕纸/纸巾", "weishengzhi juanzhi cezhi zhijin"),
        Row("🚽", "马桶/厕所", "matong cesuo"),
        Row("🚰", "自来水/水龙头/饮用水", "zilaishui shuilongtou yinyongshui"),
        Row("🚿", "淋浴/花洒/洗澡", "linyu huasa xizao"),
        Row("🛁", "浴缸/澡盆", "yugang zaopen"),
        Row("🛀", "洗澡/泡澡/沐浴", "xizao paozao muyu"),
        Row("🧼", "肥皂/香皂", "feizao xiangzao"),
        Row("🪥", "牙刷", "yashua"),
        Row("🪒", "剃须刀/刮胡刀", "tixudao guahudao"),
        Row("🧽", "海绵", "haimian"),
        Row("🪣", "水桶/桶", "shuitong tong"),
        Row("🧴", "乳液/洗发水/沐浴露", "ruye xifashui muyulu"),
        Row("🛎️", "服务铃/呼叫铃", "fuwuling hujiaoling"),
        Row("🔑", "钥匙", "yaoshi"),
        Row("🗝️", "旧钥匙/古董钥匙", "jiuyaoshi gudongyaoshi"),
        Row("🚪", "门/房门", "men fangmen"),
        Row("🪑", "椅子/凳子", "yizi dengzi"),
        Row("🛋️", "沙发", "shafa"),
        Row("🛏️", "床", "chuang"),
        Row("🛌", "睡觉/卧床", "shuijiao wochuang"),
        Row("🧸", "玩具熊/泰迪熊/小熊/毛绒玩具", "wanjuxiong taidixiong xiaoxiong maorongwanju"),
        Row("🪆", "套娃/俄罗斯套娃", "taowa eluositaowa"),
        Row("🖼️", "画/相框/油画", "hua xiangkuang youhua"),
        Row("🪞", "镜子", "jingzi"),
        Row("🪟", "窗户/窗", "chuanghu chuang"),
        Row("🛍️", "购物袋/购物/逛街", "gouwudai gouwu guangjie"),
        Row("🛒", "购物车", "gouwuche"),
        Row("🎁", "礼物/礼盒/礼品", "liwu lihe lipin"),
        Row("🎈", "气球", "qiqiu"),
        Row("🎏", "鲤鱼旗", "liyuqi"),
        Row("🎀", "蝴蝶结/丝带", "hudiejie sidai"),
        Row("🪄", "魔法棒/魔杖", "mofabang mozhang"),
        Row("🪅", "皮纳塔/彩罐", "pinata caiguan"),
        Row("🎊", "彩球/五彩纸屑", "caiqiu wucaizhixie"),
        Row("🎉", "庆祝/礼花/撒花/拉炮", "qingzhu lihua sahua lapao"),
        Row("🎎", "日本人偶/人偶", "ribenrenou renou"),
        Row("🏮", "灯笼/红灯笼", "denglong hongdenglong"),
        Row("🎐", "风铃", "fengling"),
        Row("🧧", "红包/压岁钱", "hongbao yasuiqian"),
        Row("✉️", "信封/邮件/信", "xinfeng youjian xin"),
        Row("📩", "收件", "shoujian"),
        Row("📨", "来信/新邮件", "laixin xinyoujian"),
        Row("📧", "电子邮件/邮件", "dianziyoujian youjian"),
        Row("💌", "情书", "qingshu"),
        Row("📥", "收件箱", "shoujianxiang"),
        Row("📤", "发件箱", "fajianxiang"),
        Row("📦", "包裹/快递/箱子/纸箱", "baoguo kuaidi xiangzi zhixiang"),
        Row("🏷️", "标签", "biaoqian"),
        Row("🪧", "标语牌/牌子/告示牌", "biaoyupai paizi gaoshipai"),
        Row("📪", "信箱/邮箱", "xinxiang youxiang"),
        Row("📫", "邮箱/信箱", "youxiang xinxiang"),
        Row("📬", "收信/信箱", "shouxin xinxiang"),
        Row("📭", "空信箱", "kongxinxiang"),
        Row("📮", "邮筒/邮政信箱", "youtong youzhengxinxiang"),
        Row("📯", "号角/邮政号角", "haojiao youzhenghaojiao"),
        Row("📜", "卷轴/圣旨", "juanzhou shengzhi"),
        Row("📃", "文档/纸张", "wendang zhizhang"),
        Row("📄", "文件/页面", "wenjian yemian"),
        Row("📑", "标签页/索引", "biaoqianye suoyin"),
        Row("🧾", "收据/发票/小票", "shouju fapiao xiaopiao"),
        Row("📊", "柱状图/图表/条形图", "zhuzhuangtu tubiao tiaoxingtu"),
        Row("📈", "上涨/增长/折线图", "shangzhang zengzhang zhexiantu"),
        Row("📉", "下跌/下降/暴跌", "xiadie xiajiang baodie"),
        Row("🗒️", "记事本/便签本", "jishiben bianqianben"),
        Row("🗓️", "日历/台历", "rili taili"),
        Row("📆", "日历/挂历", "rili guali"),
        Row("📅", "日历/日期/日程", "rili riqi richeng"),
        Row("🗑️", "垃圾桶/废纸篓", "lajitong feizhilou"),
        Row("📇", "名片盒/索引卡", "mingpianhe suoyinka"),
        Row("🗃️", "文件盒/档案盒/卡片盒", "wenjianhe danganhe kapianhe"),
        Row("🗳️", "投票箱/投票", "toupiaoxiang toupiao"),
        Row("🗄️", "文件柜/档案柜", "wenjiangui dangangui"),
        Row("📋", "剪贴板/写字板", "jiantieban xieziban"),
        Row("📁", "文件夹", "wenjianjia"),
        Row("📂", "打开文件夹/文件夹", "dakaiwenjianjia wenjianjia"),
        Row("🗂️", "索引夹/分类卡片", "suoyinjia fenleikapian"),
        Row("🗞️", "报纸/报纸卷", "baozhi baozhijuan"),
        Row("📰", "报纸/新闻", "baozhi xinwen"),
        Row("📓", "笔记本/本子", "bijiben benzi"),
        Row("📔", "日记本/精装笔记本", "rijiben jingzhuangbijiben"),
        Row("📒", "账本/账簿", "zhangben zhangbu"),
        Row("📕", "红皮书/书/课本", "hongpishu shu keben"),
        Row("📗", "绿皮书/书", "lvpishu shu"),
        Row("📘", "蓝皮书/书", "lanpishu shu"),
        Row("📙", "橙皮书/书", "chengpishu shu"),
        Row("📚", "书本/书籍/书堆/书", "shuben shuji shudui shu"),
        Row("📖", "看书/读书/翻开书", "kanshu dushu fankaishu"),
        Row("🔖", "书签", "shuqian"),
        Row("🧷", "别针/安全别针", "biezhen anquanbiezhen"),
        Row("🔗", "链接/连接", "lianjie lianjie"),
        Row("📎", "回形针/曲别针", "huixingzhen qubiezhen"),
        Row("🖇️", "回形针串/双回形针", "huixingzhenchuan shuanghuixingzhen"),
        Row("📐", "三角尺/三角板", "sanjiaochi sanjiaoban"),
        Row("📏", "尺子/直尺/尺", "chizi zhichi chi"),
        Row("🧮", "算盘", "suanpan"),
        Row("📌", "图钉", "tuding"),
        Row("📍", "定位/大头针/地标", "dingwei datouzhen dibiao"),
        Row("✂️", "剪刀/剪子", "jiandao jianzi"),
        Row("🖊️", "圆珠笔/笔", "yuanzhubi bi"),
        Row("🖋️", "钢笔", "gangbi"),
        Row("✒️", "笔尖/钢笔尖", "bijian gangbijian"),
        Row("🖌️", "画笔/毛笔", "huabi maobi"),
        Row("🖍️", "蜡笔", "labi"),
        Row("📝", "备忘录/笔记/记录", "beiwanglu biji jilu"),
        Row("✏️", "铅笔", "qianbi"),
        Row("🔍", "放大镜/搜索/查找", "fangdajing sousuo chazhao"),
        Row("🔎", "放大镜/搜索", "fangdajing sousuo"),
        Row("🔏", "加密/保密", "jiami baomi"),
        Row("🔐", "密码锁/安全锁", "mimasuo anquansuo"),
        Row("🔒", "锁/上锁/锁定", "suo shangsuo suoding"),
        Row("🔓", "解锁/开锁", "jiesuo kaisuo"),
        Row("🪮", "梳子/发梳", "shuzi fashu"),
    )

    private fun symbol(): List<Row> = listOf(
        Row("❤️", "红心/爱心", "hongxin aixin"),
        Row("🧡", "橙心/橙色爱心", "chengxin chengseaixin"),
        Row("💛", "黄心/黄色爱心", "huangxin huangseaixin"),
        Row("💚", "绿心/绿色爱心", "lvxin lvseaixin"),
        Row("💙", "蓝心/蓝色爱心", "lanxin lanseaixin"),
        Row("🩵", "浅蓝心/浅蓝色爱心", "qianlanxin qianlanseaixin"),
        Row("💜", "紫心/紫色爱心", "zixin ziseaixin"),
        Row("🤎", "棕心/棕色爱心", "zongxin zongseaixin"),
        Row("🖤", "黑心/黑色爱心", "heixin heiseaixin"),
        Row("🩶", "灰心/灰色爱心", "huixin huiseaixin"),
        Row("🤍", "白心/白色爱心", "baixin baiseaixin"),
        Row("🩷", "粉心/粉色爱心/粉红心", "fenxin fenseaixin fenhongxin"),
        Row("💔", "心碎/伤心/分手", "xinsui shangxin fenshou"),
        Row("❣️", "心形感叹号", "xinxinggantanhao"),
        Row("💕", "两颗心/双心", "liangkexin shuangxin"),
        Row("💞", "旋转爱心/心心相印", "xuanzhuanaixin xinxinxiangyin"),
        Row("💓", "心跳", "xintiao"),
        Row("💗", "心动/长大的心", "xindong zhangdadexin"),
        Row("💖", "闪亮爱心", "shanliangaixin"),
        Row("💘", "一箭穿心/丘比特之箭", "yijianchuanxin qiubitezhijian"),
        Row("💝", "爱心礼物/心形礼盒", "aixinliwu xinxinglihe"),
        Row("💟", "心形装饰", "xinxingzhuangshi"),
        Row("❤️‍🔥", "燃烧的心/热恋", "ranshaodexin relian"),
        Row("❤️‍🩹", "愈合的心/疗伤", "yuhedexin liaoshang"),
        Row("💢", "愤怒/青筋", "fennu qingjin"),
        Row("💥", "爆炸/碰撞", "baozha pengzhuang"),
        Row("💫", "头晕/眩晕", "touyun xuanyun"),
        Row("💦", "汗滴/水花", "handi shuihua"),
        Row("💨", "一溜烟/尾气", "yiliuyan weiqi"),
        Row("💬", "对话框/气泡", "duihuakuang qipao"),
        Row("🗨️", "左对话框", "zuoduihuakuang"),
        Row("🗯️", "愤怒对话框", "fennuduihuakuang"),
        Row("💭", "思考泡泡", "sikaopaopao"),
        Row("💤", "呼噜/睡觉/困", "hulu shuijiao kun"),
        Row("♨️", "温泉/热气", "wenquan reqi"),
        Row("💯", "满分/一百分", "manfen yibaifen"),
        Row("☮️", "和平符号/和平", "hepingfuhao heping"),
        Row("✝️", "十字架/基督教", "shizijia jidujiao"),
        Row("☪️", "星月/伊斯兰", "xingyue yisilan"),
        Row("🕉️", "奥姆/印度教", "aomu yindujiao"),
        Row("☸️", "法轮/佛教", "falun fojiao"),
        Row("✡️", "六芒星/犹太教", "liumangxing youtaijiao"),
        Row("🔯", "带点六芒星/六角星", "daidianliumangxing liujiaoxing"),
        Row("🕎", "犹太烛台/烛台", "youtaizhutai zhutai"),
        Row("☯️", "太极/阴阳/八卦", "taiji yinyang bagua"),
        Row("☦️", "东正教十字", "dongzhengjiaoshizi"),
        Row("🛐", "礼拜场所", "libaichangsuo"),
        Row("⛎", "蛇夫座", "shefuzuo"),
        Row("♈", "白羊座", "baiyangzuo"),
        Row("♉", "金牛座", "jinniuzuo"),
        Row("♊", "双子座", "shuangzizuo"),
        Row("♋", "巨蟹座", "juxiezuo"),
        Row("♌", "狮子座", "shizizuo"),
        Row("♍", "处女座", "chunvzuo"),
        Row("♎", "天秤座/天平座", "tianchengzuo tianpingzuo"),
        Row("♏", "天蝎座", "tianxiezuo"),
        Row("♐", "射手座", "sheshouzuo"),
        Row("♑", "摩羯座", "mojiezuo"),
        Row("♒", "水瓶座", "shuipingzuo"),
        Row("♓", "双鱼座", "shuangyuzuo"),
        Row("🆔", "身份标识/证件", "shenfenbiaoshi zhengjian"),
        Row("⚛️", "原子/原子符号", "yuanzi yuanzifuhao"),
        Row("🉑", "可/可接受", "ke kejieshou"),
        Row("☢️", "辐射/核辐射", "fushe hefushe"),
        Row("☣️", "生化危机/生物危害", "shenghuaweiji shengwuweihai"),
        Row("📴", "关机", "guanji"),
        Row("📳", "振动模式/震动", "zhendongmoshi zhendong"),
        Row("🈶", "有标志", "youbiaozhi"),
        Row("🈚", "无标志/无", "wubiaozhi wu"),
        Row("🈸", "申请", "shenqing"),
        Row("🈺", "营业中/营业", "yingyezhong yingye"),
        Row("🈷️", "月", "yue"),
        Row("✴️", "八角星", "bajiaoxing"),
        Row("🆚", "对战/对决", "duizhan duijue"),
        Row("🉐", "得标志/打折", "debiaozhi dazhe"),
        Row("㊙️", "秘密/秘", "mimi mi"),
        Row("㊗️", "祝贺/祝福", "zhuhe zhufu"),
        Row("🈴", "合格", "hege"),
        Row("🈵", "满员/满", "manyuan man"),
        Row("🈹", "打折/折扣", "dazhe zhekou"),
        Row("🈲", "禁止/禁", "jinzhi jin"),
        Row("🅰️", "甲型血", "jiaxingxue"),
        Row("🅱️", "乙型血", "yixingxue"),
        Row("🆎", "血型", "xuexing"),
        Row("🆑", "清除", "qingchu"),
        Row("🅾️", "欧型血", "ouxingxue"),
        Row("🆘", "求救/救命", "qiujiu jiuming"),
        Row("❌", "叉/错误/红叉", "cha cuowu hongcha"),
        Row("⭕", "红圈/圈", "hongquan quan"),
        Row("🛑", "停止标志", "tingzhibiaozhi"),
        Row("⛔", "禁止通行/禁止入内", "jinzhitongxing jinzhirunei"),
        Row("📛", "姓名牌/名牌", "xingmingpai mingpai"),
        Row("🚫", "禁止/禁止符号", "jinzhi jinzhifuhao"),
        Row("🚷", "禁止行人", "jinzhixingren"),
        Row("🚯", "禁止乱扔垃圾", "jinzhiluanrenglaji"),
        Row("🚳", "禁止自行车", "jinzhizixingche"),
        Row("🚱", "非饮用水/禁止饮用", "feiyinyongshui jinzhiyinyong"),
        Row("🔞", "十八禁/未成年人禁止", "shibajin weichengnianrenjinzhi"),
        Row("📵", "禁止手机", "jinzhishouji"),
        Row("🚭", "禁止吸烟/禁烟", "jinzhixiyan jinyan"),
        Row("❗", "感叹号/叹号", "gantanhao tanhao"),
        Row("❕", "白色感叹号", "baisegantanhao"),
        Row("❓", "问号", "wenhao"),
        Row("❔", "白色问号", "baisewenhao"),
        Row("‼️", "双感叹号", "shuanggantanhao"),
        Row("⁉️", "感叹疑问号", "gantanyiwenhao"),
        Row("🔅", "低亮度", "diliangdu"),
        Row("🔆", "高亮度/亮度", "gaoliangdu liangdu"),
        Row("〽️", "交替符号/歌记号", "jiaotifuhao gejihao"),
        Row("⚠️", "警告/注意", "jinggao zhuyi"),
        Row("🚸", "注意儿童/儿童过马路", "zhuyiertong ertongguomalu"),
        Row("🔱", "三叉戟", "sanchaji"),
        Row("⚜️", "百合花饰/鸢尾花", "baihehuashi yuanweihua"),
        Row("🔰", "新手标志/新手", "xinshoubiaozhi xinshou"),
        Row("♻️", "回收/环保", "huishou huanbao"),
        Row("✅", "对号/完成", "duihao wancheng"),
        Row("🈯", "指定", "zhiding"),
        Row("💹", "上涨/股市上涨", "shangzhang gushishangzhang"),
        Row("❇️", "闪烁/闪光", "shanshuo shanguang"),
        Row("✳️", "绿色星号", "lvsexinghao"),
        Row("❎", "叉号按钮", "chahaoanniu"),
        Row("💠", "菱形花/带点菱形", "lingxinghua daidianlingxing"),
        Row("Ⓜ️", "地铁标志", "ditiebiaozhi"),
        Row("🌀", "台风/旋涡", "taifeng xuanwo"),
        Row("🏧", "取款机/自动取款机", "qukuanji zidongqukuanji"),
        Row("🚾", "卫生间/厕所", "weishengjian cesuo"),
        Row("♿", "轮椅/无障碍/残疾人", "lunyi wuzhangai canjiren"),
        Row("🅿️", "停车场/停车", "tingchechang tingche"),
        Row("🛗", "电梯", "dianti"),
        Row("🈳", "空/空闲", "kong kongxian"),
        Row("🈂️", "服务费/服务", "fuwufei fuwu"),
        Row("🛂", "护照检查/边检", "huzhaojiancha bianjian"),
        Row("🛃", "海关", "haiguan"),
        Row("🛄", "行李提取/取行李", "xinglitiqu quxingli"),
        Row("🛅", "行李寄存/寄存", "xinglijicun jicun"),
        Row("🚹", "男厕所/男卫生间", "nancesuo nanweishengjian"),
        Row("🚺", "女厕所/女卫生间", "nvcesuo nvweishengjian"),
        Row("🚼", "母婴室/婴儿标志", "muyingshi yingerbiaozhi"),
        Row("⚧️", "跨性别标志/跨性别", "kuaxingbiebiaozhi kuaxingbie"),
        Row("🚻", "洗手间/公共厕所", "xishoujian gonggongcesuo"),
        Row("🚮", "扔垃圾/垃圾入篓", "renglaji lajirulou"),
        Row("🎦", "电影院/电影标志", "dianyingyuan dianyingbiaozhi"),
        Row("📶", "信号/信号格", "xinhao xinhaoge"),
        Row("🈁", "此处", "cichu"),
        Row("🔣", "符号/符号输入", "fuhao fuhaoshuru"),
        Row("ℹ️", "信息/信息标志", "xinxi xinxibiaozhi"),
        Row("🔤", "字母/英文字母", "zimu yingwenzimu"),
        Row("🔡", "小写字母", "xiaoxiezimu"),
        Row("🔠", "大写字母", "daxiezimu"),
        Row("🆖", "不行/失误", "buxing shiwu"),
        Row("🆗", "好的/可以", "haode keyi"),
        Row("🆙", "向上/升级", "xiangshang shengji"),
        Row("🆒", "酷按钮/酷", "kuanniu ku"),
        Row("🆕", "新/全新", "xin quanxin"),
        Row("🆓", "免费", "mianfei"),
        Row("0️⃣", "数字零", "shuziling"),
        Row("1️⃣", "数字一", "shuziyi"),
        Row("2️⃣", "数字二", "shuzier"),
        Row("3️⃣", "数字三", "shuzisan"),
        Row("4️⃣", "数字四", "shuzisi"),
        Row("5️⃣", "数字五", "shuziwu"),
        Row("6️⃣", "数字六", "shuziliu"),
        Row("7️⃣", "数字七", "shuziqi"),
        Row("8️⃣", "数字八", "shuziba"),
        Row("9️⃣", "数字九", "shuzijiu"),
        Row("🔟", "数字十", "shuzishi"),
        Row("🔢", "数字", "shuzi"),
        Row("#️⃣", "井号", "jinghao"),
        Row("*️⃣", "星号", "xinghao"),
        Row("⏏️", "弹出", "tanchu"),
        Row("▶️", "播放", "bofang"),
        Row("⏸️", "暂停", "zanting"),
        Row("⏯️", "播放暂停", "bofangzanting"),
        Row("⏹️", "停止", "tingzhi"),
        Row("⏺️", "录制", "luzhi"),
        Row("⏭️", "下一首/下一曲", "xiayishou xiayiqu"),
        Row("⏮️", "上一首/上一曲", "shangyishou shangyiqu"),
        Row("⏩", "快进", "kuaijin"),
        Row("⏪", "快退/倒带", "kuaitui daodai"),
        Row("⏫", "快速向上", "kuaisuxiangshang"),
        Row("⏬", "快速向下", "kuaisuxiangxia"),
        Row("◀️", "倒退/左三角", "daotui zuosanjiao"),
        Row("🔼", "上三角", "shangsanjiao"),
        Row("🔽", "下三角", "xiasanjiao"),
        Row("➡️", "右箭头/向右", "youjiantou xiangyou"),
        Row("⬅️", "左箭头/向左", "zuojiantou xiangzuo"),
        Row("⬆️", "上箭头/向上", "shangjiantou xiangshang"),
        Row("⬇️", "下箭头/向下", "xiajiantou xiangxia"),
        Row("↗️", "右上箭头", "youshangjiantou"),
        Row("↘️", "右下箭头", "youxiajiantou"),
        Row("↙️", "左下箭头", "zuoxiajiantou"),
        Row("↖️", "左上箭头", "zuoshangjiantou"),
        Row("↕️", "上下箭头", "shangxiajiantou"),
        Row("↔️", "左右箭头", "zuoyoujiantou"),
        Row("↪️", "右转弯箭头/右转", "youzhuanwanjiantou youzhuan"),
        Row("↩️", "左转弯箭头/左转", "zuozhuanwanjiantou zuozhuan"),
        Row("⤴️", "上弯箭头", "shangwanjiantou"),
        Row("⤵️", "下弯箭头", "xiawanjiantou"),
        Row("🔀", "随机播放/随机", "suijibofang suiji"),
        Row("🔁", "循环播放/循环", "xunhuanbofang xunhuan"),
        Row("🔂", "单曲循环", "danquxunhuan"),
        Row("🔄", "刷新", "shuaxin"),
        Row("🔃", "顺时针循环/同步", "shunshizhenxunhuan tongbu"),
        Row("🎵", "音符", "yinfu"),
        Row("🎶", "音乐/多个音符", "yinyue duogeyinfu"),
        Row("➕", "加号/加", "jiahao jia"),
        Row("➖", "减号/减", "jianhao jian"),
        Row("➗", "除号", "chuhao"),
        Row("✖️", "乘号", "chenghao"),
        Row("🟰", "等号", "denghao"),
        Row("♾️", "无限/无穷大", "wuxian wuqiongda"),
        Row("💲", "美元符号", "meiyuanfuhao"),
        Row("💱", "货币兑换/换汇", "huobiduihuan huanhui"),
        Row("™️", "商标", "shangbiao"),
        Row("©️", "版权", "banquan"),
        Row("®️", "注册商标", "zhuceshangbiao"),
        Row("〰️", "波浪线", "bolangxian"),
        Row("➰", "卷曲环", "juanquhuan"),
        Row("➿", "双卷曲环", "shuangjuanquhuan"),
        Row("🔚", "结束", "jieshu"),
        Row("🔙", "返回", "fanhui"),
        Row("🔛", "开启", "kaiqi"),
        Row("🔝", "置顶/顶部", "zhiding dingbu"),
        Row("🔜", "马上/即将", "mashang jijiang"),
        Row("✔️", "对勾/打勾", "duigou dagou"),
        Row("☑️", "勾选框/复选框", "gouxuankuang fuxuankuang"),
        Row("🔘", "单选按钮", "danxuananniu"),
        Row("🔴", "红圆/红点", "hongyuan hongdian"),
        Row("🟠", "橙圆", "chengyuan"),
        Row("🟡", "黄圆/黄点", "huangyuan huangdian"),
        Row("🟢", "绿圆/绿点", "lvyuan lvdian"),
        Row("🔵", "蓝圆/蓝点", "lanyuan landian"),
        Row("🟣", "紫圆", "ziyuan"),
        Row("⚫", "黑圆/黑点", "heiyuan heidian"),
        Row("⚪", "白圆/白点", "baiyuan baidian"),
        Row("🟤", "棕圆", "zongyuan"),
        Row("🔺", "红三角", "hongsanjiao"),
        Row("🔻", "倒三角/红倒三角", "daosanjiao hongdaosanjiao"),
        Row("🔸", "小橙菱形", "xiaochenglingxing"),
        Row("🔹", "小蓝菱形", "xiaolanlingxing"),
        Row("🔶", "大橙菱形/橙菱形", "dachenglingxing chenglingxing"),
        Row("🔷", "大蓝菱形/蓝菱形", "dalanlingxing lanlingxing"),
        Row("🔳", "白方块按钮", "baifangkuaianniu"),
        Row("🔲", "黑方块按钮", "heifangkuaianniu"),
        Row("▪️", "黑小方块", "heixiaofangkuai"),
        Row("▫️", "白小方块", "baixiaofangkuai"),
        Row("◾", "黑中小方块", "heizhongxiaofangkuai"),
        Row("◽", "白中小方块", "baizhongxiaofangkuai"),
        Row("◼️", "黑中方块", "heizhongfangkuai"),
        Row("◻️", "白中方块", "baizhongfangkuai"),
        Row("🟥", "红方块", "hongfangkuai"),
        Row("🟧", "橙方块", "chengfangkuai"),
        Row("🟨", "黄方块", "huangfangkuai"),
        Row("🟩", "绿方块", "lvfangkuai"),
        Row("🟦", "蓝方块", "lanfangkuai"),
        Row("🟪", "紫方块", "zifangkuai"),
        Row("🟫", "棕方块", "zongfangkuai"),
        Row("⬛", "黑大方块/黑方块", "heidafangkuai heifangkuai"),
        Row("⬜", "白大方块/白方块", "baidafangkuai baifangkuai"),
        Row("🔈", "扬声器/低音量", "yangshengqi diyinliang"),
        Row("🔇", "静音", "jingyin"),
        Row("🔉", "中音量/音量", "zhongyinliang yinliang"),
        Row("🔊", "大音量/高音量", "dayinliang gaoyinliang"),
        Row("🔔", "铃铛/通知", "lingdang tongzhi"),
        Row("🔕", "免打扰/禁止响铃", "miandarao jinzhixiangling"),
        Row("📣", "喇叭/扩音器", "laba kuoyinqi"),
        Row("📢", "广播/大喇叭", "guangbo dalaba"),
        Row("👁️‍🗨️", "对话眼睛/目击者", "duihuayanjing mujizhe"),
    )
}
