// SPDX-License-Identifier: GPL-3.0-only
//
// Copyright (C) 2026 lurixo
//
// This program is free software: you can redistribute it and/or modify it under
// the terms of the GNU General Public License as published by the Free Software
// Foundation, version 3.
//
// This program is distributed in the hope that it will be useful, but WITHOUT ANY
// WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
// PARTICULAR PURPOSE. See the GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License along with
// this program. If not, see <https://www.gnu.org/licenses/>.

package com.aegis.ime.engine

internal object SymbolAssociations {

    class Row(val name: String, val keys: String, vararg glyphs: String) {
        val glyphList: List<String> = glyphs.toList()
        val keyList: List<String> get() = keys.split(' ')
        val primaryKey: String get() = keys.substringBefore(' ')
    }

    fun rows(): List<Row> =
        punctuationZh() +
        punctuationEn() +
        currency() +
        net() +
        math() +
        units() +
        greek() +
        arrows() +
        superSub() +
        ordinals() +
        extendedSymbols() +
        namedVariants()

    private fun punctuationZh(): List<Row> = listOf(
        Row("逗号", "douhao", "，"),
        Row("句号", "juhao", "。"),
        Row("顿号", "dunhao", "、"),
        Row("分号", "fenhao", "；"),
        Row("冒号", "maohao", "："),
        Row("问号", "wenhao", "？"),
        Row("叹号/感叹号", "tanhao gantanhao", "！"),
        Row("引号/双引号", "yinhao shuangyinhao", "“", "”"),
        Row("单引号", "danyinhao", "‘", "’"),
        Row("括号", "kuohao", "（", "）"),
        Row("左括号", "zuokuohao", "（"),
        Row("右括号", "youkuohao", "）"),
        Row("书名号", "shuminghao", "《", "》"),
        Row("单书名号", "danshuminghao", "〈", "〉"),
        Row("直角引号", "zhijiaoyinhao", "「", "」"),
        Row("双直角引号", "shuangzhijiaoyinhao", "『", "』"),
        Row("方头括号", "fangtoukuohao", "【", "】"),
        Row("空心方头括号", "kongxinfangtoukuohao", "〖", "〗"),
        Row("六角括号", "liujiaokuohao", "〔", "〕"),
        Row("省略号", "shenglvehao", "…"),
        Row("破折号", "pozhehao", "—"),
        Row("波浪号", "bolanghao", "～"),
        Row("间隔号", "jiangehao", "·"),
        Row("双竖线", "shuangshuxian", "‖"),
        Row("下划线", "xiahuaxian", "＿"),
        Row("波浪线", "bolangxian", "﹏", "﹋"),
        Row("井号", "jinghao", "＃"),
        Row("星号", "xinghao", "＊"),
        Row("艾特", "aite", "＠"),
        Row("百分号", "baifenhao", "％"),
        Row("加号", "jiahao", "＋"),
        Row("等号", "denghao", "＝"),
        Row("竖线/管道符", "shuxian guandaofu", "｜"),
        Row("小于号", "xiaoyuhao", "＜"),
        Row("大于号", "dayuhao", "＞"),
        Row("斜杠/斜线", "xiegang xiexian", "／"),
        Row("反斜杠/反斜线", "fanxiegang fanxiexian", "＼"),
        Row("反引号", "fanyinhao", "｀"),
    )

    private fun punctuationEn(): List<Row> = listOf(
        Row("中括号/方括号", "zhongkuohao fangkuohao", "［", "］"),
        Row("大括号/花括号", "dakuohao huakuohao", "｛", "｝"),
        Row("尖括号", "jiankuohao", "＜", "＞"),
        Row("脱字符", "tuozifu", "^"),
        Row("连字符", "lianzifu", "-"),
        Row("减号", "jianhao", "−"),
        Row("项目符号/圆点", "xiangmufuhao yuandian", "•", "·"),
        Row("连接号", "lianjiehao", "–"),
        Row("章节号/分节号", "zhangjiehao fenjiehao", "§"),
        Row("段落号", "duanluohao", "¶"),
        Row("商标号/商标", "shangbiaohao shangbiao", "™", "®"),
        Row("版权号/版权", "banquanhao banquan", "©"),
        Row("注册商标", "zhuceshangbiao", "®"),
        Row("美金", "meijin", "\$"),
    )

    private fun currency(): List<Row> = listOf(
        Row("日元", "riyuan", "¥", "円"),
        Row("英镑", "yingbang", "£"),
        Row("韩元", "hanyuan", "₩"),
        Row("卢比/印度卢比", "lubi yindulubi", "₹"),
        Row("卢布", "lubu", "₽"),
        Row("里拉", "lila", "₺", "₤"),
        Row("泰铢", "taizhu", "฿"),
        Row("越南盾", "yuenandun", "₫"),
        Row("格里夫纳", "gelifuna", "₴"),
        Row("奈拉", "naila", "₦"),
        Row("美分", "meifen", "¢"),
        Row("比索", "bisuo", "₱"),
        Row("谢克尔", "xiekeer", "₪"),
        Row("坚戈", "jiange", "₸"),
        Row("图格里克", "tugelike", "₮"),
        Row("基普", "jipu", "₭"),
        Row("瓜拉尼", "gualani", "₲"),
        Row("科朗", "kelang", "₡"),
        Row("塞地", "saidi", "₵"),
        Row("比特币", "bitebi", "₿"),
        Row("里亚尔", "liyaer", "﷼"),
        Row("法郎", "falang", "₣"),
        Row("密尔", "mier", "₥"),
        Row("人民币", "renminbi", "￥"),
    )

    private fun net(): List<Row> = listOf(
        Row("网址", "wangzhi", "http://", "https://"),
    )

    private fun math(): List<Row> = listOf(
        Row("乘号", "chenghao", "×"),
        Row("叉/错号", "cha cuohao", "×"),
        Row("除号", "chuhao", "÷"),
        Row("不等于/不等号", "budengyu budenghao", "≠"),
        Row("约等于/约等号/约等", "yuedengyu yuedenghao yuedeng", "≈", "≒"),
        Row("恒等于/恒等号", "hengdengyu hengdenghao", "≡"),
        Row("正负号/正负", "zhengfuhao zhengfu", "±"),
        Row("负正号", "fuzhenghao", "∓"),
        Row("小于等于", "xiaoyudengyu", "≤"),
        Row("大于等于", "dayudengyu", "≥"),
        Row("小于", "xiaoyu", "<"),
        Row("大于", "dayu", ">"),
        Row("无穷/无穷大/无限", "wuqiong wuqiongda wuxian", "∞"),
        Row("根号/平方根", "genhao pingfanggen", "√"),
        Row("对勾/对号", "duigou duihao", "√"),
        Row("立方根", "lifanggen", "∛"),
        Row("求和", "qiuhe", "∑"),
        Row("连乘/求积", "liancheng qiuji", "∏"),
        Row("积分/积分号", "jifen jifenhao", "∫"),
        Row("二重积分", "erchongjifen", "∬"),
        Row("三重积分", "sanchongjifen", "∭"),
        Row("环路积分/曲线积分", "huanlujifen quxianjifen", "∮"),
        Row("偏导/偏导数", "piandao piandaoshu", "∂"),
        Row("倒三角/纳布拉", "daosanjiao nabula", "∇"),
        Row("千分号/千分之", "qianfenhao qianfenzhi", "‰"),
        Row("正比于/成正比", "zhengbiyu chengzhengbi", "∝"),
        Row("所以", "suoyi", "∴"),
        Row("因为", "yinwei", "∵"),
        Row("角", "jiao", "∠"),
        Row("垂直", "chuizhi", "⊥"),
        Row("平行", "pingxing", "∥"),
        Row("角分", "jiaofen", "′"),
        Row("角秒", "jiaomiao", "″"),
        Row("圆周率", "yuanzhoulv", "π"),
        Row("二分之一", "erfenzhiyi", "½"),
        Row("三分之一", "sanfenzhiyi", "⅓"),
        Row("四分之一", "sifenzhiyi", "¼"),
        Row("四分之三", "sifenzhisan", "¾"),
        Row("三分之二", "sanfenzhier", "⅔"),
        Row("属于", "shuyu", "∈"),
        Row("不属于", "bushuyu", "∉"),
        Row("真包含于", "zhenbaohanyu", "⊂"),
        Row("真包含", "zhenbaohan", "⊃"),
        Row("包含于", "baohanyu", "⊆"),
        Row("包含", "baohan", "⊇"),
        Row("并集", "bingji", "∪"),
        Row("交集", "jiaoji", "∩"),
        Row("空集", "kongji", "∅"),
        Row("任意", "renyi", "∀"),
        Row("存在", "cunzai", "∃"),
        Row("全等", "quandeng", "≅"),
        Row("相似", "xiangsi", "∽"),
        Row("异或/直和", "yihuo zhihe", "⊕"),
        Row("张量积", "zhangliangji", "⊗"),
        Row("实数集", "shishuji", "ℝ"),
        Row("自然数集", "ziranshuji", "ℕ"),
        Row("整数集", "zhengshuji", "ℤ"),
        Row("有理数集", "youlishuji", "ℚ"),
        Row("复数集", "fushuji", "ℂ"),
        Row("正弦", "zhengxian", "sin"),
        Row("余弦", "yuxian", "cos"),
        Row("正切", "zhengqie", "tan"),
        Row("余切", "yuqie", "cot"),
        Row("正割", "zhengge", "sec"),
        Row("余割", "yuge", "csc"),
        Row("反正弦", "fanzhengxian", "arcsin"),
        Row("反余弦", "fanyuxian", "arccos"),
        Row("反正切", "fanzhengqie", "arctan"),
        Row("双曲正弦", "shuangquzhengxian", "sinh"),
        Row("双曲余弦", "shuangquyuxian", "cosh"),
        Row("双曲正切", "shuangquzhengqie", "tanh"),
    )

    private fun units(): List<Row> = listOf(
        Row("摄氏度", "sheshidu", "℃"),
        Row("华氏度", "huashidu", "℉"),
        Row("千克/公斤", "qianke gongjin", "㎏"),
        Row("毫米", "haomi", "㎜"),
        Row("厘米/公分", "limi gongfen", "㎝"),
        Row("千米/公里", "qianmi gongli", "㎞"),
        Row("平方米/平米", "pingfangmi pingmi", "㎡"),
        Row("立方米", "lifangmi", "㎥"),
        Row("毫克", "haoke", "㎎"),
        Row("毫升", "haosheng", "㎖"),
    )

    private fun greek(): List<Row> = listOf(
        Row("阿尔法", "aerfa", "α", "Α"),
        Row("贝塔", "beita", "β", "Β"),
        Row("伽马", "gama", "γ", "Γ"),
        Row("德尔塔", "deerta", "δ", "Δ", "∆"),
        Row("伊普西龙", "yipuxilong", "ε", "Ε"),
        Row("泽塔", "zeta", "ζ", "Ζ"),
        Row("伊塔", "yita", "η", "Η"),
        Row("西塔", "xita", "θ", "Θ"),
        Row("约塔", "yueta", "ι", "Ι"),
        Row("卡帕", "kapa", "κ", "Κ"),
        Row("拉姆达/兰姆达", "lamuda lanmuda", "λ", "Λ"),
        Row("缪", "miu", "μ", "Μ"),
        Row("希腊字母纽", "xilazimuniu", "ν", "Ν"),
        Row("克西", "kexi", "ξ", "Ξ"),
        Row("奥米克戎", "aomikerong", "ο", "Ο"),
        Row("派", "pai", "π", "Π"),
        Row("希腊字母柔", "xilazimurou", "ρ", "Ρ"),
        Row("西格玛", "xigema", "σ", "Σ", "ς"),
        Row("陶", "tao", "τ", "Τ"),
        Row("宇普西龙", "yupuxilong", "υ", "Υ"),
        Row("斐", "fei", "φ", "Φ"),
        Row("卡方", "kafang", "χ"),
        Row("希腊字母凯", "xilazimukai", "χ", "Χ"),
        Row("普西", "puxi", "ψ", "Ψ"),
        Row("欧米伽", "oumijia", "ω", "Ω"),
        Row("欧姆", "oumu", "Ω"),
    )

    private fun arrows(): List<Row> = listOf(
        Row("箭头", "jiantou", "→", "←", "↑"),
        Row("左箭头", "zuojiantou", "←", "⬅"),
        Row("右箭头", "youjiantou", "→", "➡"),
        Row("上箭头", "shangjiantou", "↑", "⬆"),
        Row("下箭头", "xiajiantou", "↓", "⬇"),
        Row("左右箭头", "zuoyoujiantou", "↔"),
        Row("上下箭头", "shangxiajiantou", "↕"),
        Row("左上箭头", "zuoshangjiantou", "↖"),
        Row("右上箭头", "youshangjiantou", "↗"),
        Row("右下箭头", "youxiajiantou", "↘"),
        Row("左下箭头", "zuoxiajiantou", "↙"),
        Row("双箭头", "shuangjiantou", "⇒", "⇐", "⇔"),
        Row("右双箭头", "youshuangjiantou", "⇒"),
        Row("左双箭头", "zuoshuangjiantou", "⇐"),
        Row("上双箭头", "shangshuangjiantou", "⇑"),
        Row("下双箭头", "xiashuangjiantou", "⇓"),
        Row("左右双箭头", "zuoyoushuangjiantou", "⇔"),
        Row("上下双箭头", "shangxiashuangjiantou", "⇕"),
        Row("左弯箭头", "zuowanjiantou", "↩"),
        Row("右弯箭头", "youwanjiantou", "↪"),
        Row("上弯箭头", "shangwanjiantou", "⤴"),
        Row("下弯箭头", "xiawanjiantou", "⤵"),
        Row("逆时针", "nishizhen", "↺", "↶"),
        Row("顺时针", "shunshizhen", "↻", "↷"),
        Row("长箭头", "changjiantou", "⟶", "⟵"),
    )

    private fun superSub(): List<Row> = listOf(
        Row("平方", "pingfang", "²"),
        Row("立方", "lifang", "³"),
        Row("上标0", "shangbiaoling", "⁰"),
        Row("上标1", "shangbiaoyi", "¹"),
        Row("上标2", "shangbiaoer", "²"),
        Row("上标3", "shangbiaosan", "³"),
        Row("上标4", "shangbiaosi", "⁴"),
        Row("上标5", "shangbiaowu", "⁵"),
        Row("上标6", "shangbiaoliu", "⁶"),
        Row("上标7", "shangbiaoqi", "⁷"),
        Row("上标8", "shangbiaoba", "⁸"),
        Row("上标9", "shangbiaojiu", "⁹"),
        Row("下标0", "xiabiaoling", "₀"),
        Row("下标1", "xiabiaoyi", "₁"),
        Row("下标2", "xiabiaoer", "₂"),
        Row("下标3", "xiabiaosan", "₃"),
        Row("下标4", "xiabiaosi", "₄"),
        Row("下标5", "xiabiaowu", "₅"),
        Row("下标6", "xiabiaoliu", "₆"),
        Row("下标7", "xiabiaoqi", "₇"),
        Row("下标8", "xiabiaoba", "₈"),
        Row("下标9", "xiabiaojiu", "₉"),
    )

    private fun ordinals(): List<Row> = listOf(
        Row("圈一~圈二十", "quanyi", "①", "❶"),
        Row("", "quaner", "②", "❷"),
        Row("", "quansan", "③", "❸"),
        Row("", "quansi", "④", "❹"),
        Row("", "quanwu", "⑤", "❺"),
        Row("", "quanliu", "⑥", "❻"),
        Row("", "quanqi", "⑦", "❼"),
        Row("", "quanba", "⑧", "❽"),
        Row("", "quanjiu", "⑨", "❾"),
        Row("", "quanshi", "⑩", "❿"),
        Row("", "quanshiyi", "⑪"),
        Row("", "quanshier", "⑫"),
        Row("", "quanshisan", "⑬"),
        Row("", "quanshisi", "⑭"),
        Row("", "quanshiwu", "⑮"),
        Row("", "quanshiliu", "⑯"),
        Row("", "quanshiqi", "⑰"),
        Row("", "quanshiba", "⑱"),
        Row("", "quanshijiu", "⑲"),
        Row("", "quanershi", "⑳"),
        Row("括号一~括号十(全角汉字/半角数字两式)", "kuohaoyi", "㈠", "⑴"),
        Row("", "kuohaoer", "㈡", "⑵"),
        Row("", "kuohaosan", "㈢", "⑶"),
        Row("", "kuohaosi", "㈣", "⑷"),
        Row("", "kuohaowu", "㈤", "⑸"),
        Row("", "kuohaoliu", "㈥", "⑹"),
        Row("", "kuohaoqi", "㈦", "⑺"),
        Row("", "kuohaoba", "㈧", "⑻"),
        Row("", "kuohaojiu", "㈨", "⑼"),
        Row("", "kuohaoshi", "㈩", "⑽"),
        Row("罗马数字一~十(1-5 带小写)", "luomashuziyi", "Ⅰ", "ⅰ"),
        Row("", "luomashuzier", "Ⅱ", "ⅱ"),
        Row("", "luomashuzisan", "Ⅲ", "ⅲ"),
        Row("", "luomashuzisi", "Ⅳ", "ⅳ"),
        Row("", "luomashuziwu", "Ⅴ", "ⅴ"),
        Row("", "luomashuziliu", "Ⅵ", "ⅵ"),
        Row("", "luomashuziqi", "Ⅶ", "ⅶ"),
        Row("", "luomashuziba", "Ⅷ", "ⅷ"),
        Row("", "luomashuzijiu", "Ⅸ", "ⅸ"),
        Row("", "luomashuzishi", "Ⅹ", "ⅹ"),
    )

    private fun extendedSymbols(): List<Row> = listOf(
        Row("全角中括号", "quanjiaozhongkuohao", "［", "］"),
        Row("全角大括号", "quanjiaodakuohao", "｛", "｝"),
        Row("虚线", "xuxian", "┄"),
        Row("长音符", "changyinfu", "¯"),
        Row("转交", "zhuanjiao", "℅"),
        Row("双六角括号", "shuangliujiaokuohao", "〘", "〙"),
        Row("两点省略号", "liangdianshenglvehao", "‥"),
        Row("雌性/女性符号", "cixing nvxingfuhao", "♀"),
        Row("雄性/男性符号", "xiongxing nanxingfuhao", "♂"),
        Row("不小于", "buxiaoyu", "≮"),
        Row("不大于", "budayu", "≯"),
        Row("比号", "bihao", "∶"),
        Row("比例号", "bilihao", "∷"),
        Row("万分号", "wanfenhao", "‱"),
        Row("不真包含于", "buzhenbaohanyu", "⊄"),
        Row("不真包含", "buzhenbaohan", "⊅"),
        Row("不包含于", "bubaohanyu", "⊈"),
        Row("不包含", "bubaohan", "⊉"),
        Row("真子集", "zhenziji", "⊊"),
        Row("真超集", "zhenchaoji", "⊋"),
        Row("逻辑与", "luojiyu", "∧"),
        Row("逻辑或", "luojihuo", "∨"),
        Row("曲面积分", "qumianjifen", "∯"),
        Row("体积分", "tijifen", "∰"),
        Row("直角", "zhijiao", "∟"),
        Row("直角三角形", "zhijiaosanjiaoxing", "⊿"),
        Row("三角形", "sanjiaoxing", "△"),
        Row("圆弧", "yuanhu", "⌒"),
        Row("对数", "duishu", "log"),
        Row("自然对数", "ziranduishu", "ln"),
        Row("极限", "jixian", "lim"),
        Row("微米", "weimi", "㎛"),
        Row("立方厘米", "lifanglimi", "㏄"),
        Row("摩尔", "moer", "㏖"),
        Row("密耳", "mier", "㏕"),
        Row("罗马数字十一", "luomashuzishiyi", "Ⅺ", "ⅺ"),
        Row("罗马数字十二", "luomashuzishier", "Ⅻ", "ⅻ"),
    )

    private fun namedVariants(): List<Row> = listOf(
        Row("英文逗号", "yingwendouhao", ","),
        Row("英文句号/句点", "yingwenjuhao judian", "."),
        Row("英文问号", "yingwenwenhao", "?"),
        Row("英文叹号/英文感叹号", "yingwentanhao yingwengantanhao", "!"),
        Row("英文分号", "yingwenfenhao", ";"),
        Row("英文冒号", "yingwenmaohao", ":"),
        Row("英文引号/英文双引号/直引号", "yingwenyinhao yingwenshuangyinhao zhiyinhao", "\""),
        Row("英文单引号/撇号", "yingwendanyinhao piehao", "'"),
        Row("英文括号", "yingwenkuohao", "(", ")"),
        Row("英文左括号", "yingwenzuokuohao", "("),
        Row("英文右括号", "yingwenyoukuohao", ")"),
        Row("英文中括号/英文方括号", "yingwenzhongkuohao yingwenfangkuohao", "[", "]"),
        Row("英文大括号/英文花括号", "yingwendakuohao yingwenhuakuohao", "{", "}"),
        Row("英文尖括号", "yingwenjiankuohao", "<", ">"),
        Row("英文下划线", "yingwenxiahuaxian", "_"),
        Row("英文斜杠/英文斜线", "yingwenxiegang yingwenxiexian", "/"),
        Row("英文反斜杠/英文反斜线", "yingwenfanxiegang yingwenfanxiexian", "\\"),
        Row("英文竖线/英文管道符", "yingwenshuxian yingwenguandaofu", "|"),
        Row("英文艾特", "yingwenaite", "@"),
        Row("英文井号", "yingwenjinghao", "#"),
        Row("英文星号", "yingwenxinghao", "*"),
        Row("英文百分号", "yingwenbaifenhao", "%"),
        Row("英文加号", "yingwenjiahao", "+"),
        Row("英文等号", "yingwendenghao", "="),
        Row("英文减号", "yingwenjianhao", "-"),
        Row("英文波浪号", "yingwenbolanghao", "~"),
        Row("英文反引号", "yingwenfanyinhao", "`"),
        Row("与号/和号", "yuhao hehao", "＆"),
        Row("英文与号/英文和号", "yingwenyuhao yingwenhehao", "&"),
        Row("左引号/左双引号", "zuoyinhao zuoshuangyinhao", "“"),
        Row("右引号/右双引号", "youyinhao youshuangyinhao", "”"),
        Row("左单引号", "zuodanyinhao", "‘"),
        Row("右单引号", "youdanyinhao", "’"),
        Row("法式引号/双燕尾号", "fashiyinhao shuangyanweihao", "«", "»"),
        Row("法式单引号/单燕尾号", "fashidanyinhao danyanweihao", "‹", "›"),
        Row("锐音符", "ruiyinfu", "´"),
        Row("分音符", "fenyinfu", "¨"),
        Row("倒感叹号", "daogantanhao", "¡"),
        Row("倒问号", "daowenhao", "¿"),
        Row("断竖线", "duanshuxian", "¦"),
        Row("抑扬符/倒扬抑符", "yiyangfu daoyangyifu", "ˇ"),
        Row("参考符号/米印", "cankaofuhao miyin", "※"),
        Row("同上符号/重复符号", "tongshangfuhao chongfufuhao", "〃"),
        Row("欧洲货币单位", "ouzhouhuobidanwei", "₠"),
        Row("元字符", "yuanzifu", "元"),
        Row("圆字符", "yuanzifu", "圆"),
        Row("圆点运算符/圈点", "yuandianyunsuanfu quandian", "⊙"),
        Row("上标加号", "shangbiaojiahao", "⁺"),
        Row("上标减号", "shangbiaojianhao", "⁻"),
        Row("上标等号", "shangbiaodenghao", "⁼"),
        Row("上标左括号", "shangbiaozuokuohao", "⁽"),
        Row("上标右括号", "shangbiaoyoukuohao", "⁾"),
        Row("上标字母a", "shangbiaozimua shangbiaoa", "ᵃ"),
        Row("上标字母b", "shangbiaozimubi shangbiaobi", "ᵇ"),
        Row("上标字母c", "shangbiaozimuxi shangbiaoxi", "ᶜ"),
        Row("上标字母d", "shangbiaozimudi shangbiaodi", "ᵈ"),
        Row("上标字母e", "shangbiaozimuyi shangbiaoyi", "ᵉ"),
        Row("上标字母f", "shangbiaozimuaifu shangbiaoaifu", "ᶠ"),
        Row("上标字母g", "shangbiaozimuji shangbiaoji", "ᵍ"),
        Row("上标字母h", "shangbiaozimuaichi shangbiaoaichi", "ʰ"),
        Row("上标字母i", "shangbiaozimuai shangbiaoai", "ⁱ"),
        Row("上标字母j", "shangbiaozimujie shangbiaojie", "ʲ"),
        Row("上标字母k", "shangbiaozimukai shangbiaokai", "ᵏ"),
        Row("上标字母l", "shangbiaozimuaile shangbiaoaile", "ˡ"),
        Row("上标字母m", "shangbiaozimuaimu shangbiaoaimu", "ᵐ"),
        Row("上标字母n", "shangbiaozimuen shangbiaoen", "ⁿ"),
        Row("上标字母o", "shangbiaozimuou shangbiaoou", "ᵒ"),
        Row("上标字母p", "shangbiaozimupi shangbiaopi", "ᵖ"),
        Row("上标字母r", "shangbiaozimuaer shangbiaoaer", "ʳ"),
        Row("上标字母s", "shangbiaozimuaisi shangbiaoaisi", "ˢ"),
        Row("上标字母t", "shangbiaozimuti shangbiaoti", "ᵗ"),
        Row("上标字母u", "shangbiaozimuyou shangbiaoyou", "ᵘ"),
        Row("上标字母v", "shangbiaozimuwei shangbiaowei", "ᵛ"),
        Row("上标字母w", "shangbiaozimudabuliu shangbiaodabuliu", "ʷ"),
        Row("上标字母x", "shangbiaozimuaikesi shangbiaoaikesi", "ˣ"),
        Row("上标字母y", "shangbiaozimuwai shangbiaowai", "ʸ"),
        Row("上标字母z", "shangbiaozimuzeide shangbiaozeide", "ᶻ"),
        Row("上标齿擦音", "shangbiaochicayin", "ᶞ"),
        Row("上标大写字母A", "shangbiaodaxiezimua shangbiaodaxiea", "ᴬ"),
        Row("上标大写字母B", "shangbiaodaxiezimubi shangbiaodaxiebi", "ᴮ"),
        Row("上标大写字母D", "shangbiaodaxiezimudi shangbiaodaxiedi", "ᴰ"),
        Row("上标大写字母E", "shangbiaodaxiezimuyi shangbiaodaxieyi", "ᴱ"),
        Row("上标大写字母G", "shangbiaodaxiezimuji shangbiaodaxieji", "ᴳ"),
        Row("上标大写字母H", "shangbiaodaxiezimuaichi shangbiaodaxieaichi", "ᴴ"),
        Row("上标大写字母I", "shangbiaodaxiezimuai shangbiaodaxieai", "ᴵ"),
        Row("上标大写字母J", "shangbiaodaxiezimujie shangbiaodaxiejie", "ᴶ"),
        Row("上标大写字母K", "shangbiaodaxiezimukai shangbiaodaxiekai", "ᴷ"),
        Row("上标大写字母L", "shangbiaodaxiezimuaile shangbiaodaxieaile", "ᴸ"),
        Row("上标大写字母M", "shangbiaodaxiezimuaimu shangbiaodaxieaimu", "ᴹ"),
        Row("上标大写字母N", "shangbiaodaxiezimuen shangbiaodaxieen", "ᴺ"),
        Row("上标大写字母O", "shangbiaodaxiezimuou shangbiaodaxieou", "ᴼ"),
        Row("上标大写字母P", "shangbiaodaxiezimupi shangbiaodaxiepi", "ᴾ"),
        Row("上标大写字母R", "shangbiaodaxiezimuaer shangbiaodaxieaer", "ᴿ"),
        Row("上标大写字母T", "shangbiaodaxiezimuti shangbiaodaxieti", "ᵀ"),
        Row("上标大写字母U", "shangbiaodaxiezimuyou shangbiaodaxieyou", "ᵁ"),
        Row("上标大写字母V", "shangbiaodaxiezimuwei shangbiaodaxiewei", "ⱽ"),
        Row("上标大写字母W", "shangbiaodaxiezimudabuliu shangbiaodaxiedabuliu", "ᵂ"),
        Row("下标加号", "xiabiaojiahao", "₊"),
        Row("下标减号", "xiabiaojianhao", "₋"),
        Row("下标等号", "xiabiaodenghao", "₌"),
        Row("下标左括号", "xiabiaozuokuohao", "₍"),
        Row("下标右括号", "xiabiaoyoukuohao", "₎"),
        Row("下标字母a", "xiabiaozimua xiabiaoa", "ₐ"),
        Row("下标字母e", "xiabiaozimuyi xiabiaoyi", "ₑ"),
        Row("下标字母h", "xiabiaozimuaichi xiabiaoaichi", "ₕ"),
        Row("下标字母i", "xiabiaozimuai xiabiaoai", "ᵢ"),
        Row("下标字母j", "xiabiaozimujie xiabiaojie", "ⱼ"),
        Row("下标字母k", "xiabiaozimukai xiabiaokai", "ₖ"),
        Row("下标字母l", "xiabiaozimuaile xiabiaoaile", "ₗ"),
        Row("下标字母m", "xiabiaozimuaimu xiabiaoaimu", "ₘ"),
        Row("下标字母n", "xiabiaozimuen xiabiaoen", "ₙ"),
        Row("下标字母o", "xiabiaozimuou xiabiaoou", "ₒ"),
        Row("下标字母p", "xiabiaozimupi xiabiaopi", "ₚ"),
        Row("下标字母r", "xiabiaozimuaer xiabiaoaer", "ᵣ"),
        Row("下标字母s", "xiabiaozimuaisi xiabiaoaisi", "ₛ"),
        Row("下标字母t", "xiabiaozimuti xiabiaoti", "ₜ"),
        Row("下标字母u", "xiabiaozimuyou xiabiaoyou", "ᵤ"),
        Row("下标字母v", "xiabiaozimuwei xiabiaowei", "ᵥ"),
        Row("下标字母x", "xiabiaozimuaikesi xiabiaoaikesi", "ₓ"),
        Row("下标央元音", "xiabiaoyangyuanyin", "ₔ"),
        Row("下标伽马", "xiabiaogama", "ᵧ"),
        Row("点式序号一", "dianshixuhaoyi", "⒈"),
        Row("点式序号二", "dianshixuhaoer", "⒉"),
        Row("点式序号三", "dianshixuhaosan", "⒊"),
        Row("点式序号四", "dianshixuhaosi", "⒋"),
        Row("点式序号五", "dianshixuhaowu", "⒌"),
        Row("点式序号六", "dianshixuhaoliu", "⒍"),
        Row("点式序号七", "dianshixuhaoqi", "⒎"),
        Row("点式序号八", "dianshixuhaoba", "⒏"),
        Row("点式序号九", "dianshixuhaojiu", "⒐"),
        Row("点式序号十", "dianshixuhaoshi", "⒑"),
        Row("大写一", "daxieyi", "壹"),
        Row("大写二", "daxieer", "贰"),
        Row("大写三", "daxiesan", "叁"),
        Row("大写四", "daxiesi", "肆"),
        Row("大写五", "daxiewu", "伍"),
        Row("大写六", "daxieliu", "陆"),
        Row("大写七", "daxieqi", "柒"),
        Row("大写八", "daxieba", "捌"),
        Row("大写九", "daxiejiu", "玖"),
        Row("大写十", "daxieshi", "拾"),
        Row("大写百", "daxiebai", "佰"),
        Row("大写千", "daxieqian", "仟"),
        Row("大写万", "daxiewan", "万"),
        Row("大写亿", "daxieyi", "亿"),
        Row("繁体大写二", "fantidaxieer", "貳"),
        Row("繁体大写三", "fantidaxiesan", "參"),
        Row("繁体大写六", "fantidaxieliu", "陸"),
        Row("繁体大写万", "fantidaxiewan", "萬"),
        Row("繁体大写亿", "fantidaxieyi", "億"),
        Row("圈大写字母A", "quandaxiezimua", "Ⓐ"),
        Row("圈大写字母B", "quandaxiezimubi", "Ⓑ"),
        Row("圈大写字母C", "quandaxiezimuxi", "Ⓒ"),
        Row("圈小写字母a", "quanxiaoxiezimua", "ⓐ"),
        Row("圈小写字母b", "quanxiaoxiezimubi", "ⓑ"),
        Row("圈小写字母c", "quanxiaoxiezimuxi", "ⓒ"),
        Row("上右下左箭头", "shangyouxiazuojiantou", "⇄"),
        Row("上左下右箭头", "shangzuoxiayoujiantou", "⇆"),
        Row("左上右下箭头", "zuoshangyouxiajiantou", "⇅"),
        Row("左下右上箭头", "zuoxiayoushangjiantou", "⇵"),
        Row("左双头箭头", "zuoshuangtoujiantou", "↞"),
        Row("右双头箭头", "youshuangtoujiantou", "↠"),
        Row("上双头箭头", "shangshuangtoujiantou", "↟"),
        Row("下双头箭头", "xiashuangtoujiantou", "↡"),
        Row("上三头箭头", "shangsantoujiantou", "⤊"),
        Row("下三头箭头", "xiasantoujiantou", "⤋"),
        Row("带尾左箭头", "daiweizuojiantou", "↢"),
        Row("带尾右箭头", "daiweiyoujiantou", "↣"),
        Row("从竖线向左箭头", "congshuxianxiangzuojiantou", "↤"),
        Row("映射箭头/从竖线向右箭头", "yingshejiantou congshuxianxiangyoujiantou", "↦"),
        Row("从横线向上箭头", "conghengxianxiangshangjiantou", "↥"),
        Row("从横线向下箭头", "conghengxianxiangxiajiantou", "↧"),
        Row("向上左拐箭头", "xiangshangzuoguaijiantou", "↰"),
        Row("向上右拐箭头", "xiangshangyouguaijiantou", "↱"),
        Row("向下左拐箭头", "xiangxiazuoguaijiantou", "↲"),
        Row("向下右拐箭头", "xiangxiayouguaijiantou", "↳"),
        Row("左波浪箭头", "zuobolangjiantou", "↜"),
        Row("右波浪箭头", "youbolangjiantou", "↝"),
        Row("左曲线箭头", "zuoquxianjiantou", "⇜"),
        Row("右曲线箭头", "youquxianjiantou", "⇝"),
        Row("否定双向箭头", "foudingshuangxiangjiantou", "⇎"),
        Row("空心左箭头", "kongxinzuojiantou", "⇦"),
        Row("空心右箭头", "kongxinyoujiantou", "⇨"),
        Row("空心上箭头", "kongxinshangjiantou", "⇧"),
        Row("空心下箭头", "kongxinxiajiantou", "⇩"),
        Row("带横线上箭头/大写锁定符号", "daihengxianshangjiantou daxiesuodingfuhao", "⇪"),
        Row("粗宽头右箭头", "cukuantouyoujiantou", "➔"),
        Row("粗圆头右箭头", "cuyuantouyoujiantou", "➜"),
        Row("三角头右箭头", "sanjiaotouyoujiantou", "➝"),
        Row("粗三角头右箭头", "cusanjiaotouyoujiantou", "➞"),
        Row("虚线三角头右箭头", "xuxiansanjiaotouyoujiantou", "➟"),
        Row("粗虚线三角头右箭头", "cuxuxiansanjiaotouyoujiantou", "➠"),
        Row("顶光立体右箭头", "dingguanglitiyoujiantou", "➢"),
        Row("底光立体右箭头", "diguanglitiyoujiantou", "➣"),
        Row("实心右箭头头", "shixinyoujiantoutou", "➤"),
        Row("粗下弯右箭头", "cuxiawanyoujiantou", "➥"),
        Row("粗上弯右箭头", "cushangwanyoujiantou", "➦"),
        Row("短粗右箭头", "duancuyoujiantou", "➧"),
        Row("粗凹尖右箭头", "cuaojianyoujiantou", "➨"),
        Row("右阴影空心右箭头", "youyinyingkongxinyoujiantou", "➩"),
        Row("左阴影空心右箭头", "zuoyinyingkongxinyoujiantou", "➪"),
        Row("后倾阴影右箭头", "houqingyinyingyoujiantou", "➫"),
        Row("前倾阴影右箭头", "qianqingyinyingyoujiantou", "➬"),
        Row("粗右下阴影右箭头", "cuyouxiayinyingyoujiantou", "➭"),
        Row("粗右上阴影右箭头", "cuyoushangyinyingyoujiantou", "➮"),
        Row("缺口右下阴影右箭头", "quekouyouxiayinyingyoujiantou", "➯"),
        Row("缺口右上阴影右箭头", "quekouyoushangyinyingyoujiantou", "➱"),
        Row("圆圈右箭头", "yuanquanyoujiantou", "➲"),
        Row("白羽右箭头", "baiyuyoujiantou", "➳"),
        Row("黑羽右下箭头", "heiyuyouxiajiantou", "➴"),
        Row("黑羽右箭头", "heiyuyoujiantou", "➵"),
        Row("黑羽右上箭头", "heiyuyoushangjiantou", "➶"),
        Row("粗黑羽右下箭头", "cuheiyuyouxiajiantou", "➷"),
        Row("粗黑羽右箭头", "cuheiyuyoujiantou", "➸"),
        Row("粗黑羽右上箭头", "cuheiyuyoushangjiantou", "➹"),
        Row("泪滴倒钩右箭头", "leididaogouyoujiantou", "➺"),
        Row("粗泪滴尾右箭头", "culeidiweiyoujiantou", "➻"),
        Row("楔尾右箭头", "xieweiyoujiantou", "➼"),
        Row("粗楔尾右箭头", "cuxieweiyoujiantou", "➽"),
        Row("开口轮廓右箭头", "kaikoulunkuoyoujiantou", "➾"),
        Row("左指手势符号", "zuozhishoushifuhao", "☜"),
        Row("右指手势符号", "youzhishoushifuhao", "☞"),
        Row("上指手势符号", "shangzhishoushifuhao", "☝"),
        Row("下指手势符号", "xiazhishoushifuhao", "☟"),
        Row("竖排逗号", "shupaidouhao", "︐"),
        Row("竖排句号", "shupaijuhao", "︒"),
        Row("竖排顿号", "shupaidunhao", "︑"),
        Row("竖排冒号", "shupaimaohao", "︓"),
        Row("竖排分号", "shupaifenhao", "︔"),
        Row("竖排感叹号", "shupaigantanhao", "︕"),
        Row("竖排问号", "shupaiwenhao", "︖"),
        Row("竖排省略号", "shupaishenglvehao", "︙"),
        Row("竖排两点省略号", "shupailiangdianshenglvehao", "︰"),
        Row("竖排左括号", "shupaizuokuohao", "︵"),
        Row("竖排右括号", "shupaiyoukuohao", "︶"),
        Row("竖排左大括号", "shupaizuodakuohao", "︷"),
        Row("竖排右大括号", "shupaiyoudakuohao", "︸"),
        Row("竖排左六角括号", "shupaizuoliujiaokuohao", "︹"),
        Row("竖排右六角括号", "shupaiyouliujiaokuohao", "︺"),
        Row("竖排左单书名号", "shupaizuodanshuminghao", "︿"),
        Row("竖排右单书名号", "shupaiyoudanshuminghao", "﹀"),
        Row("竖排左书名号", "shupaizuoshuminghao", "︽"),
        Row("竖排右书名号", "shupaiyoushuminghao", "︾"),
        Row("竖排左直角引号", "shupaizuozhijiaoyinhao", "﹁"),
        Row("竖排右直角引号", "shupaiyouzhijiaoyinhao", "﹂"),
        Row("竖排左双直角引号", "shupaizuoshuangzhijiaoyinhao", "﹃"),
        Row("竖排右双直角引号", "shupaiyoushuangzhijiaoyinhao", "﹄"),
        Row("竖排左方头括号", "shupaizuofangtoukuohao", "︻"),
        Row("竖排右方头括号", "shupaiyoufangtoukuohao", "︼"),
        Row("竖排左空心方头括号", "shupaizuokongxinfangtoukuohao", "︗"),
        Row("竖排右空心方头括号", "shupaiyoukongxinfangtoukuohao", "︘"),
        Row("竖排左方括号", "shupaizuofangkuohao", "﹇"),
        Row("竖排右方括号", "shupaiyoufangkuohao", "﹈"),
        Row("竖排破折号", "shupaipozhehao", "︱"),
        Row("竖排连接号", "shupailianjiehao", "︲"),
        Row("竖排下划线", "shupaixiahuaxian", "︳"),
        Row("竖排波浪下划线", "shupaibolangxiahuaxian", "︴"),
        Row("虚线上划线", "xuxianshanghuaxian", "﹉"),
        Row("点划上划线", "dianhuashanghuaxian", "﹊"),
        Row("双波浪上划线", "shuangbolangshanghuaxian", "﹌"),
        Row("虚线下划线", "xuxianxiahuaxian", "﹍"),
        Row("点划下划线", "dianhuaxiahuaxian", "﹎"),
        Row("全角长音符", "quanjiaochangyinfu", "￣"),
        Row("长后开不圆唇元音/长啊音", "changhoukaibuyuanchunyuanyin changayin", "ɑː"),
        Row("长后半开圆唇元音/长哦音", "changhoubankaiyuanchunyuanyin changoyin", "ɔː"),
        Row("长央半开不圆唇元音/长央元音", "changyangbankaibuyuanchunyuanyin changyangyuanyin", "ɜː"),
        Row("长前闭不圆唇元音/长衣音", "changqianbibuyuanchunyuanyin changyiyin", "iː"),
        Row("长后闭圆唇元音/长乌音", "changhoubiyuanchunyuanyin changwuyin", "uː"),
        Row("后半开不圆唇元音/倒音标维", "houbankaibuyuanchunyuanyin daoyinbiaowei", "ʌ"),
        Row("后开圆唇元音", "houkaiyuanchunyuanyin", "ɒ"),
        Row("中央元音", "zhongyangyuanyin", "ə"),
        Row("次闭前不圆唇元音/短衣音", "cibiqianbuyuanchunyuanyin duanyiyin", "ɪ"),
        Row("次闭后圆唇元音/短乌音", "cibihouyuanchunyuanyin duanwuyin", "ʊ"),
        Row("前半闭不圆唇元音", "qianbanbibuyuanchunyuanyin", "e"),
        Row("前次开不圆唇元音/蝴蝶音", "qiancikaibuyuanchunyuanyin hudieyin", "æ"),
        Row("合口双元音诶", "hekoushuangyuanyinei", "eɪ"),
        Row("合口双元音爱", "hekoushuangyuanyinai", "aɪ"),
        Row("合口双元音哦衣", "hekoushuangyuanyinoyi", "ɔɪ"),
        Row("集中双元音衣额", "jizhongshuangyuanyinyie", "ɪə"),
        Row("集中双元音诶额", "jizhongshuangyuanyineie", "eə"),
        Row("集中双元音乌额", "jizhongshuangyuanyinwue", "ʊə"),
        Row("合口双元音额乌", "hekoushuangyuanyinewu", "əʊ"),
        Row("合口双元音奥", "hekoushuangyuanyinao", "aʊ"),
        Row("清双唇爆破音", "qingshuangchunbaopoyin", "p"),
        Row("浊双唇爆破音", "zhuoshuangchunbaopoyin", "b"),
        Row("清齿龈爆破音", "qingchiyinbaopoyin", "t"),
        Row("浊齿龈爆破音", "zhuochiyinbaopoyin", "d"),
        Row("清软腭爆破音", "qingruanebaopoyin", "k"),
        Row("浊软腭爆破音", "zhuoruanebaopoyin", "g"),
        Row("清唇齿擦音", "qingchunchicayin", "f"),
        Row("浊唇齿擦音", "zhuochunchicayin", "v"),
        Row("浊齿擦音", "zhuochicayin", "ð"),
        Row("清齿龈擦音", "qingchiyincayin", "s"),
        Row("浊齿龈擦音", "zhuochiyincayin", "z"),
        Row("清龈后擦音", "qingyinhoucayin", "ʃ"),
        Row("浊龈后擦音", "zhuoyinhoucayin", "ʒ"),
        Row("清声门擦音", "qingshengmencayin", "h"),
        Row("双唇鼻音", "shuangchunbiyin", "m"),
        Row("齿龈鼻音", "chiyinbiyin", "n"),
        Row("软腭鼻音/后鼻音", "ruanebiyin houbiyin", "ŋ"),
        Row("齿龈边近音", "chiyinbianjinyin", "l"),
        Row("齿龈颤音", "chiyinchanyin", "r"),
        Row("硬腭近音", "yingejinyin", "j"),
        Row("唇软腭近音", "chunruanejinyin", "w"),
        Row("清齿龈塞擦音", "qingchiyinsecayin", "ts"),
        Row("浊齿龈塞擦音", "zhuochiyinsecayin", "dz"),
        Row("清龈后塞擦音", "qingyinhousecayin", "tʃ"),
        Row("浊龈后塞擦音", "zhuoyinhousecayin", "dʒ"),
        Row("清齿龈爆破近音组合", "qingchiyinbaopojinyinzuhe", "tr"),
        Row("浊齿龈爆破近音组合", "zhuochiyinbaopojinyinzuhe", "dr"),
        Row("主重音符", "zhuzhongyinfu", "ˈ"),
        Row("次重音符", "cizhongyinfu", "ˌ"),
        Row("长音标记", "changyinbiaoji", "ː"),
        Row("半长音标记", "banchangyinbiaoji", "ˑ"),
        Row("前闭不圆唇元音", "qianbibuyuanchunyuanyin", "i"),
        Row("前半开不圆唇元音", "qianbankaibuyuanchunyuanyin", "ɛ"),
        Row("央半开不圆唇元音", "yangbankaibuyuanchunyuanyin", "ɜ"),
        Row("后开不圆唇元音", "houkaibuyuanchunyuanyin", "ɑ"),
        Row("后半开圆唇元音", "houbankaiyuanchunyuanyin", "ɔ"),
        Row("后半闭圆唇元音", "houbanbiyuanchunyuanyin", "o"),
        Row("后闭圆唇元音", "houbiyuanchunyuanyin", "u"),
        Row("前闭圆唇元音", "qianbiyuanchunyuanyin", "y"),
        Row("前半闭圆唇元音", "qianbanbiyuanchunyuanyin", "ø"),
        Row("浊龈后塞擦音合字", "zhuoyinhousecayinhezi", "ʤ"),
        Row("清龈后塞擦音合字", "qingyinhousecayinhezi", "ʧ"),
        Row("清硬腭擦音", "qingyingecayin", "ç"),
        Row("清软腭擦音", "qingruanecayin", "x"),
        Row("浊软腭擦音", "zhuoruanecayin", "ɣ"),
        Row("声门塞音/喉塞音", "shengmenseyin houseyin", "ʔ"),
        Row("齿龈近音", "chiyinjinyin", "ɹ"),
        Row("软腭化齿龈边近音/暗边音", "ruanehuachiyinbianjinyin anbianyin", "ɫ"),
        Row("硬腭鼻音", "yingebiyin", "ɲ"),
        Row("清齿擦音", "qingchicayin", "θ"),
        Row("拼音啊", "pinyina", "a"),
        Row("拼音啊一声", "pinyinayisheng", "ā"),
        Row("拼音啊二声", "pinyinaersheng", "á"),
        Row("拼音啊三声", "pinyinasansheng", "ǎ"),
        Row("拼音啊四声", "pinyinasisheng", "à"),
        Row("拼音喔", "pinyino", "o"),
        Row("拼音喔一声", "pinyinoyisheng", "ō"),
        Row("拼音喔二声", "pinyinoersheng", "ó"),
        Row("拼音喔三声", "pinyinosansheng", "ǒ"),
        Row("拼音喔四声", "pinyinosisheng", "ò"),
        Row("拼音鹅", "pinyine", "e"),
        Row("拼音鹅一声", "pinyineyisheng", "ē"),
        Row("拼音鹅二声", "pinyineersheng", "é"),
        Row("拼音鹅三声", "pinyinesansheng", "ě"),
        Row("拼音鹅四声", "pinyinesisheng", "è"),
        Row("拼音诶/带帽拼音鹅", "pinyinei daimaopinyine", "ê"),
        Row("拼音衣", "pinyinyi", "i"),
        Row("拼音衣一声", "pinyinyiyisheng", "ī"),
        Row("拼音衣二声", "pinyinyiersheng", "í"),
        Row("拼音衣三声", "pinyinyisansheng", "ǐ"),
        Row("拼音衣四声", "pinyinyisisheng", "ì"),
        Row("拼音乌", "pinyinwu", "u"),
        Row("拼音乌一声", "pinyinwuyisheng", "ū"),
        Row("拼音乌二声", "pinyinwuersheng", "ú"),
        Row("拼音乌三声", "pinyinwusansheng", "ǔ"),
        Row("拼音乌四声", "pinyinwusisheng", "ù"),
        Row("拼音迂", "pinyinyu", "ü"),
        Row("拼音迂一声", "pinyinyuyisheng", "ǖ"),
        Row("拼音迂二声", "pinyinyuersheng", "ǘ"),
        Row("拼音迂三声", "pinyinyusansheng", "ǚ"),
        Row("拼音迂四声", "pinyinyusisheng", "ǜ"),
        Row("拼音恩", "pinyinen", "n"),
        Row("拼音恩二声", "pinyinenersheng", "ń"),
        Row("拼音恩三声", "pinyinensansheng", "ň"),
        Row("拼音恩四声", "pinyinensisheng", "ǹ"),
        Row("拼音姆二声", "pinyinmuersheng", "ḿ"),
    )
}
